### ISSUE TITLE
ol Native Instance Provisioning

### ISSUE THREAD

**Issue by itmanyong** [MelihAltintas/vue3-openlayers#100]
**Is your feature request related to a problem? Please describe.**
Add native instance references to the REF of component layers, controls and tools, so that the methods and properties of native instances can be called quickly and accurately.

**Describe the solution you'd like**
Such as:
1. To call the abortDrawing native method of DRAW, obtain it from the MAP instance and then find the corresponding DRAW instance for calling. If the corresponding native instance is provided in the REF of the Draw component, this will be done

**Describe alternatives you've considered**
1. or provide it centrally in a ref on <ol-map />? That would be fine, but it might be better to define unique names for the components that need to be used. As follows
```
<ol-map ref="olMapRef">

    <ol-vector-layer>

        <ol-source-vector :projection="projection">

            <ol-interaction-draw name="device">

            </ol-interaction-draw>

        </ol-source-vector>
    </ol-vector-layer>
</ol-map>
const olMapRef = ref() // {...,device:drawInstance}
```
**Additional context**
![image](https://user-images.githubusercontent.com/53500371/188078307-615a22ef-2622-4237-9263-4ac7233a4b49.png)

**Comment by mostafaznv** [comment]
most needed feature.

**Comment by d-koppenhagen** [comment]
The DrawInteraction as well as other Interactions and Components will `provide` you the feature you need:
https://github.com/MelihAltintas/vue3-openlayers/blob/17c9106e0c7db728b1671683a51b13c53d7612fc/src/components/interaction/DrawInteraction.vue#L110

```vue
<script setup>
import { inject } from "vue";
// ...
const draw = provide("stylable");
</script>
```

With this, you should be able to access the native Draw Instance.

PS:
you can also inject the `Map` instance instead of accessing it through a `ref`:

```vue
<script setup>
import { inject } from "vue";
// ...
const map = inject("map"); // ol.Map
// ...
</script>
```
