### ISSUE TITLE
Set map control position

### ISSUE THREAD

**Issue by Trayshar** [MelihAltintas/vue3-openlayers#101]
**Is your feature request related to a problem? Please describe.**
Dynamically set where map controls like zoom, fullscreen, etc are positioned

**Describe the solution you'd like**
[Openlayers itself uses css](https://openlayers.org/en/latest/apidoc/module-ol_control_Control-Control.html) for positioning; Expose a way to overwrite it with props, either class-based or directly: 
```html
    <ol-fullscreen-control position-class="my-custom-css-class" />
    <ol-scaleline-control  top="0.5em" left="1em" />
```
I'd prefer the second, direct option.

**Describe alternatives you've considered**
Alternative: Add a `position` prop to the map control components. The order the components are declared defines the order they are rendered in if they both have the same position:
```html
    <ol-fullscreen-control position="top left" />
    <ol-scaleline-control  position="bottom left"/>
    <ol-zoom-control  position="top left" /> <!-- Same position as fullscreen-control, but declared later, so rendered below it -->
    <ol-attribution-control  position="bottom right"/>
```

**Additional context**
Couldn't find anything on this in the docs or github issues/discussions. My attempts to overwrite the CSS manually with `style` or `class` prop didn't work.

**Comment by d-koppenhagen** [comment]
Positioning can be done using customized class names and CSS.
Please refer to the docs: https://vue3openlayers.netlify.app/componentsguide/mapcontrols/fullscreen/
