### ISSUE TITLE
Render data inside map at absolute position

### ISSUE THREAD

**Issue by Trayshar** [MelihAltintas/vue3-openlayers#102]
**Is your feature request related to a problem? Please describe.**
I'd like to add a small card-like container inside the map at an absolute position to display details, like the attribution control element does. Just with multiple rows of text or other HTML

**Describe the solution you'd like**
Add a new control element that renders its children inside the map.
```
<ol-control-container>
  Some HTML, maybe a container, idk
<ol-control-container />
```

**Describe alternatives you've considered**
Just put my own HTML inside it, without the control element. [OpenLayers advises to wrap it inside a control](https://openlayers.org/en/latest/apidoc/module-ol_control_Control-Control.html)

Or go the cursed route: Use `<ol-overlay>` and update it's position everytime the map moves to stay where it should be.

**Additional context**
This probably depends on #101

**Comment by d-koppenhagen** [comment]
Hey, can't you just add a bit of CSS to place you element at absolute position above the Map? So it shouldn't be specific to OpenLayers, it's simply CSS isn't it?

**Comment by d-koppenhagen** [comment]
As there was no response I will close this issue. In my opinion, the placement should/can be done with CSS styling.
