### ISSUE TITLE
ReferenceError in HeatmapLayer

### ISSUE THREAD

**Issue by muellerat91interactive** [MelihAltintas/vue3-openlayers#103]
**Describe the bug**
~~If `:updateWhileAnimating="true" :updateWhileInteracting="true"` is enabled~~ on the HeatmapLayer a `ReferenceError` occurs when the value of the `blur` or `radius` prop is changed.
https://github.com/MelihAltintas/vue3-openlayers/blob/main/src/components/layers/HeatmapLayer.vue#L34
Edit: Seems like a typo! `hetmapLayer` instead of `heatmapLayer`

**To Reproduce**
1. Use the `ol-heatmap-layer`
~~2. Enable `:updateWhileAnimating="true" :updateWhileInteracting="true"`~~
3. Change value of  `blur` or `radius` prop

**Expected behavior**
Updated heatmaplayer with new `blur` or `radius` values.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome 
 - Version 105.0.5195.102

**Additional context**
[127.0.0.1-1662995060394.log](https://github.com/MelihAltintas/vue3-openlayers/files/9549299/127.0.0.1-1662995060394.log)

**Comment by jschirrmacher** [comment]
I can confirm that. It's a typo preventing the heatmap to update when properties are changed.
