### ISSUE TITLE
Hit Tolerance in interaction-select

### ISSUE THREAD

**Issue by aocneanu** [MelihAltintas/vue3-openlayers#104]
Hello,

I'm probably not doing something right, but I cannot use `:hit-tolerance="xx"` on the select interaction.

Could anybody point me in the right direction?

Thank you!

**Comment by aocneanu** [comment]
Looking more, I guess this feature is [not supported](https://github.com/MelihAltintas/vue3-openlayers/blob/main/src/components/interaction/SelectInteraction.vue#L69) (hitTolerance)

**Comment by MelihAltintas** [comment]
please update 0.1.71
