### ISSUE TITLE
<ol-mouseposition-control /> How set coordinateFormat ???

### ISSUE THREAD

**Issue by KirillDorfman** [MelihAltintas/vue3-openlayers#106]
How set coordinateFormat ???
Add :coordinateFormat="" dont work.

**Comment by jerryfaust** [comment]
I got this to work using a format function in my 'methods' section (note that the className allows me to apply a style)

`    <ol-mouseposition-control className="mouseposition" projection="EPSG:4326" :coordinateFormat="formatCoord" />
`

Then import a helper function from OpenLayers

`import { toStringXY } from 'ol/coordinate'
`

and finally, in the 'methods' section

`    formatCoord(coordinate) {
      return toStringXY(coordinate, 5);
    },
`
