### ISSUE TITLE
vue3-openlayers.es.js:2828 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by NeluQi** [MelihAltintas/vue3-openlayers#110]
![image](https://user-images.githubusercontent.com/16963395/195586877-0065d5cc-ea40-4f69-bbcc-fb8ec0f53432.png)

![image](https://user-images.githubusercontent.com/16963395/195586922-4624f08e-7100-46c8-a2b0-8711a754d09a.png)

LayerGroup2.prototype.handleLayersRemove_ = function(collectionEvent) {
    var layer = collectionEvent.element;
    var key = getUid(layer);
    this.listenerKeys_[key].forEach(unlistenByKey);
    delete this.listenerKeys_[key];
    this.dispatchEvent(new GroupEvent("removelayer", layer));
    this.changed();
  };
  LayerGroup2.prototype.get

**Comment by d-koppenhagen** [comment]
@NeluQi can you give a bit more context or provide a minimalistic example how to reproduce this problem?
You can e.g. for this Stackblitz project: https://stackblitz.com/edit/vitejs-vite-9wrqog?file=src/components/TheMap.vue

**Comment by d-koppenhagen** [comment]
As of no response, I will close this issue for now. Please re-open if the problem still exists and provide more details (see comment before).
