### ISSUE TITLE
ol-style-text font string has no effect

### ISSUE THREAD

**Issue by mkarliner** [MelihAltintas/vue3-openlayers#114]
**Describe the bug**
The font property of ol-style-text does not seem to have any effect.
It seems to always default to bold sans-serif

**To Reproduce**
     <ol-style-text  :font="fstyle" :text="snr" ></ol-style-text>

    const fstyle = computed(() => {
      return "italic 30px  serif;"

    })

**Expected behavior**
An italic serifed font should appear,

**Screenshots**
![image](https://user-images.githubusercontent.com/1651042/199003833-9194cbff-e40c-4dce-a644-9fecf706562e.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 1-6

**Comment by d-koppenhagen** [comment]
Please omit the `;`. This will work, just tried it out.

```html
<ol-style-text text="Hellooooo" font="italic 30px serif"></ol-style-text>
```
