### ISSUE TITLE
view reference null after remounting my component

### ISSUE THREAD

**Issue by bluelemonade** [MelihAltintas/vue3-openlayers#116]
hi,

first of all, very nice  vue implementation.

ok, I am using ref to the view, when I open the component I can use viewRef.value.setZoom() to set the zoom from an external UI. 
when I close the component and open it wirh a new map, the refView is null! inside the map everything is fine. 

how should i unmount the view?

    <div class="map-container">
        
        <ol-map :loadTilesWhileAnimating="true" :loadTilesWhileInteracting="true" style="height:980px" >
            
            <ol-view ref="viewRef" :center="center" :rotation="rotation" :zoom="zoom" :maxZoom="maxZoom" :minZoom="minZoom" :projection="projection" :extent="extent" :showFullExtent="true" :smoothResolutionConstraint="true" @zoomChanged="onZoomChanged"  @resolutionChanged="onResolutionChanged"/>
            
            

            <ol-overlay :position="position">
                <template v-slot="slotProps">
                
                    <div class="marker" :xxx="slotProps"></div>
                    
                </template>
            </ol-overlay>

            <ol-image-layer>
                
                <ol-source-image-static :url="imgUrl" :imageSize="size" :imageExtent="imageExtent" :projection="projection"></ol-source-image-static>
            </ol-image-layer>

        </ol-map>

    </div>
    
</template>

**Comment by bluelemonade** [comment]
one point, when using the mounted method of the Options Api, I get the ref of the view

mounted (){
        console.log("zoom", this.$refs.viewRef.getZoom())
        this.mainRef = this.$refs.viewRef;
        console.log("mainRef", this.mainRef)
    }

is there a  way to pass this to a property inside the setup?

**Comment by d-koppenhagen** [comment]
Have you tried to access this in a `$nextTick()`?

You can also use `inject` to access the view programatically in Vue:

```
const map = inject("map");
const view = map.getView();
```

**Comment by d-koppenhagen** [comment]
As of no response, I will close this issue for now. Please re-open if the problem still exists and provide more details (see comment before).
