### ISSUE TITLE
Visible prop of ol-tile-layer is not reactive - controls initial visibility only

### ISSUE THREAD

**Issue by gc-sommer** [MelihAltintas/vue3-openlayers#120]
**Describe the bug**
The prop visible of ol-tile-layer controls the visibility of a layer only on initial loading.

**To Reproduce**
1. Create template with ol-tile-layer

```html

<template>
    <ol-map
      ref="olMap"
      :load-tiles-while-animating="true"
      :load-tiles-while-interacting="true"
      style="height: 100%"
    >
      <ol-view
        ref="view"
        :center="center"
        :rotation="rotation"
        :zoom="zoom"
        :projection="projection"
        @zoomChanged="zoomChanged"
        @centerChanged="centerChanged"
      />

      <ol-tile-layer ref="osmlayer" title="OpenstreetMap" :visible="osmVisible">
        <ol-source-osm />
      </ol-tile-layer>

  </ol-map>
</template>
<script>
import "vue3-openlayers/dist/vue3-openlayers.css";

export default {
  name: "MapView",
  props: {
    center: {
      type: Array,
      required: true,
    },
    zoom: {
      type: Number,
      required: true,
    },
    extent: {
      type: Array,
      required: true,
    },
  },
  data() {
    return {
      rotation: 0,
      projection: "EPSG:3857",
      osmVisible: true
     },
  },
  methods: {
}
};
</script>
```

**Expected behavior**
The prop visible of ol-tile-layer controls the visibility of a layer every time the property is changing.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser Chrome 107.0.5304.87 (64-Bit), Firefox  107.0 (64-bit)

**Comment by kevinelliott** [comment]
@gc-sommer Did you ever find a solution to this?

**Comment by gc-sommer** [comment]
Hi @kevinelliott,

well the workaround is setting the visibility to true and storing the reference of the layer. In combination with a watch method you can control the visibility on the openlayers layer object by yourself (`layer.setVisible(visible);`).

Best regards,
Johannes

**Comment by kevinelliott** [comment]
@gc-sommer Thanks for the quick reply. Got it, that makes sense.

**Comment by d-koppenhagen** [comment]
@MelihAltintas was this re-opened accidently? from the comments it seems to be solved already?

**Comment by aleksmelnyk** [comment]
in 0.1.74 the issue still present. visible not reactive.

**Comment by d-koppenhagen** [comment]
I created a small stackblitz project for reproduction of your error:
https://stackblitz.com/edit/vitejs-vite-9wrqog?file=src%2Fcomponents%2FTheMap.vue

The problem is not the reactivity (it works fine).

The problem is, that you set `style="height: 100%"`. This will cause the map to have an height of 0 the very first time it renders. When you define the `style="height: 400px"` for example it works.
Also it will render when placing the whole map (with 100% height) in a container element with a defined height (e.g. `<div style="height: 200px;">...</div>`.

**Comment by boris612** [comment]
> I created a small stackblitz project for reproduction of your error: https://stackblitz.com/edit/vitejs-vite-9wrqog?file=src%2Fcomponents%2FTheMap.vue
> 
> The problem is not the reactivity (it works fine).
> 
> The problem is, that you set `style="height: 100%"`. This will cause the map to have an height of 0 the very first time it renders. When you define the `style="height: 400px"` for example it works. Also it will render when placing the whole map (with 100% height) in a container element with a defined height (e.g. `<div style="height: 200px;">...</div>`.

The initial question was about reactivity of _visible_ property. For example, add the following lines to your example on Stackblitz
```
{{ osmVisible}}
  <input type="checkbox" v-model="osmVisible"/>
```
As gc-sommer suggested, unchecking the checkbox should hide OSM map.

**Comment by boris612** [comment]
> Hi @kevinelliott,
> 
> well the workaround is setting the visibility to true and storing the reference of the layer. In combination with a watch method you can control the visibility on the openlayers layer object by yourself (`layer.setVisible(visible);`).
> 
> Best regards, Johannes

Another workaround is to use _v-if_ on _ol-tile-layer_. It will show or hide a layer, but "hidden" layer will not be available in built in layer switcher.
