### ISSUE TITLE
Use the ol-ext library

### ISSUE THREAD

**Issue by PabMai** [MelihAltintas/vue3-openlayers#125]
I need to use the ol-ext library, what would be the recommendations to add these features. I am currently trying to add a pie chart.

I would like the components to be implemented with ol-ext

**Comment by dejvlamm** [comment]
The implementation already includes ol-ext. In package.json: "ol-ext": "^3.2.24",

**Comment by MelihAltintas** [comment]
"ol-ext": "^4.0.4" is used
