### ISSUE TITLE
How to access feature from inside ol-interaction-select block?

### ISSUE THREAD

**Issue by kevinelliott** [MelihAltintas/vue3-openlayers#127]
I am trying to change the size of an icon when it is hovered over. I'm using the ol-interaction-select without issue, and I can specify a new icon altogether. However, since I have many feature types, I am struggling to figure out how to access the highlighted feature's icon from inside the select, so that I can resize the icon.

```
      <ol-interaction-select @select="featureSelected" :condition="selectCondition" :filter="selectInteractionFilter">
        <ol-style>
            <ol-style-stroke color="green" :width="10"></ol-style-stroke>
            <ol-style-fill color="rgba(255,255,255,0.5)"></ol-style-fill>
            <ol-style-icon :src="feature.properties.icon" :scale="0.05"></ol-style-icon>
        </ol-style>
      </ol-interaction-select>
```

Something like this would be helpful. But maybe there is already a way that I am not aware of?

**Comment by kevinelliott** [comment]
I would like to just modify the existing icon on hover to be slightly larger, and maybe adjust the color.

**Comment by d-koppenhagen** [comment]
Have you tried to use the [`overrideStyleFunction`](https://vue3openlayers.netlify.app/componentsguide/styles/style/#overridestylefunction) on `ol-style`? It receives a feature as the first parameter and the original style as the second. You should be able to update the `style` with it.

**Comment by d-koppenhagen** [comment]
As of no response, I will close this issue for now. Please re-open if the problem still exists and provide more details (see comment before).
