### ISSUE TITLE
Icons disappearing for features that have custom properties

### ISSUE THREAD

**Issue by kevinelliott** [MelihAltintas/vue3-openlayers#128]
The icons for features are disappearing on subsequent loads when there are properties defined on them.

For example:

```
      <ol-vector-layer>
        <ol-source-vector ref="airframesFlightsSourceVector">
          <ol-feature v-for="flight in props.airframesFlights" :key="`airframes_flight_${flight.id}`" :properties="{ id: flight.id, featureType: 'airframes-flight', icon: aircraftIcon, airframesFlightId: flight.id }">
            <ol-geom-point :coordinates="[flight.longitude, flight.latitude]" />
            <ol-style>
              <ol-style-icon
                :src="aircraftIcon"
                :anchor="[0.5, 0.5]"
                :scale="0.05"
                :rotation="flight.track"
                />
            </ol-style>
          </ol-feature>
        </ol-source-vector>
      </ol-vector-layer>
```

**Comment by jayli3n** [comment]
Im also experiencing this issue 😶‍🌫️

**Comment by jayli3n** [comment]
Bit of a workaround for now, please lmk if theres a better solution.

```
const featureRef = ref<any>()
const id= computed(() => props.xxx.id)

watch([featureRef, id], () => {
    if (!featureRef.value || !id.value) return
    featureRef.value.feature.setProperties({ id: id.value })
})
```

```
<ol-feature ref="featureRef">
        ...
</ol-feature>
```

**Comment by neeco1991** [comment]
> Bit of a workaround for now, please lmk if theres a better solution.
> 
> ```
> const featureRef = ref<any>()
> const id= computed(() => props.xxx.id)
> 
> watch([featureRef, id], () => {
>     if (!featureRef.value || !id.value) return
>     featureRef.value.feature.setProperties({ id: id.value })
> })
> ```
> 
> ```
> <ol-feature ref="featureRef">
>         ...
> </ol-feature>
> ```

I had a similar issue with the `opacity` property on an `ol-image-layer` and this solved my problem.

Love you.

**Comment by d-koppenhagen** [comment]
@kevinelliott sorry probably I didn't catch the problem. Can you please provide an example repo or fork this Stackblitz for reproduction to show the problem:
https://stackblitz.com/edit/vue3-openlayers-template?file=src%2Fcomponents%2FTheMap.vue

**Comment by toktaktk** [comment]
I am also facing the same issue . Does any one know if the solution has been found yet?

**Comment by d-koppenhagen** [comment]
Can one provide a playground for reproduction? You can fork my stackblitz project:
https://stackblitz.com/edit/vue3-openlayers-template?file=src%2Fcomponents%2FTheMap.vue

**Comment by mathiash98** [comment]
So the core issue is that we create a new `new Feature({ ...properties.properties })` in `OlFeature.vue` every time `props.properties` is replaced by a new array.
- The workaround described above works as the `props.properties` array is modified and not replaced, this does not trigger the watcher in `usePropsAsObjectProperties.ts` and does not trigger creating a new Feature object without style.

-> The new feature will not have any styles applied to itself and then the icon disappears. 

Here is reproducible code:
<details>

```Vue

<!-- modified IconDemo.vue -->
<template>
  <button @click="changeCoordinatesBreaking" type="button">
    change coordinates breaking
  </button>
  <br />
  <button @click="changeCoordinatesNotBreaking" type="button">
    change coordinates working
  </button>
  <br />
  <ol-map
    ref="map"
    :loadTilesWhileAnimating="true"
    :loadTilesWhileInteracting="true"
    style="height: 500px"
  >
    <ol-view
      ref="view"
      :center="center"
      :rotation="rotation"
      :zoom="zoom"
      :projection="projection"
    />

    <ol-vector-layer>
      <ol-source-vector>
        <ol-feature
          v-for="flight in airframesFlights"
          :key="`airframes_flight_${flight.id}`"
          :properties="{
            id: flight.id,
            featureType: 'airframes-flight',
            icon: markerIcon,
            airframesFlightId: flight.id,
          }"
        >
          <ol-geom-point :coordinates="[flight.longitude, flight.latitude]" />
          <ol-style>
            <ol-style-icon :src="markerIcon" :scale="0.1"></ol-style-icon>
          </ol-style>
        </ol-feature>
      </ol-source-vector>
    </ol-vector-layer>
  </ol-map>
</template>

<script setup lang="ts">
import { ref } from "vue";

import markerIcon from "@/assets/marker.png";

const center = ref([40, 40]);
const projection = ref("EPSG:4326");
const zoom = ref(6.8);
const rotation = ref(0);

const airframesFlights = ref([
  {
    id: "abc",
    latitude: 40,
    longitude: 40,
  },
]);

function changeCoordinatesBreaking() {
  airframesFlights.value = [
    {
      id: "abc",
      latitude: airframesFlights.value[0].latitude + 0.1,
      longitude: airframesFlights.value[0].longitude + 0.1,
    },
  ];
}
function changeCoordinatesNotBreaking() {
  airframesFlights.value[0].latitude += 0.1;
}
</script>

```

</details>


## To fix it:
- [ ] Prevent OlFeature to create a new feature on props.properties change
- [ ] Update the original Feature's properties in props.properties change

Creating a PR now
