### ISSUE TITLE
Update to OL 7.2.2 and ol-ext 4.0.4

### ISSUE THREAD

**Issue by 1Map** [MelihAltintas/vue3-openlayers#132]
https://github.com/MelihAltintas/vue3-openlayers/blob/eb300feeecb9d1b6747857568af47b8bdea5a8d2/package.json#L54

https://github.com/MelihAltintas/vue3-openlayers/blob/eb300feeecb9d1b6747857568af47b8bdea5a8d2/package.json#L56

**Comment by MelihAltintas** [comment]
0.1.72 version is up to date
