### ISSUE TITLE
layer name attribute

### ISSUE THREAD

**Issue by acebelowzero** [MelihAltintas/vue3-openlayers#14]
is it possible for you to add a the prop name to each of the layer types. 

This will help with labeling and identifying layers.

Thanks!

**Comment by akc4** [comment]
@acebelowzero you could use the `ref` parameter.

**Comment by acebelowzero** [comment]
I did use it but it would still be very useful to have the name prop. thanks tho!
@akc4

**Comment by MelihAltintas** [comment]
Normally layers don't have the name prop.  https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html but i could add as a property  if you tell me the benefits

**Comment by acebelowzero** [comment]
In my case, I wanted to make a layer selector or switcher. This allows be to switch between different maps and toggle on and off different layers. Without a name I am not able to identify what layer is what.

What I did was use a ref on each layer and added the name property my self and was able to make layer switcher, but when you're working with lots of layers like 20, its a lot of refs to add. adding the name prop to each LayerType will avoid that.

**Comment by akc4** [comment]
@acebelowzero I am guessing you have an array, you could add an extra value to each element like `showLayer: false` and simply add a `v-if="showLayer"` to your layers and trigger them how you want.

Or an array of refs.

```
:ref="el =>  layersRef[i] = el"
```

**Comment by acebelowzero** [comment]
That kinda what I did.
then I injected the map ref into my layer-switcher component. since ol-map uses the provider property.
Thanks! @akc4

**Comment by MelihAltintas** [comment]
Layer switcher is a good feature. I will add this extension (https://viglino.github.io/ol-ext/examples/control/map.switcher.image.html) to vue3-openlayers. You can easily add a layer switcher :)

**Comment by MelihAltintas** [comment]
I added layer switcher to demo page :) please update 0.1.38 :)
