### ISSUE TITLE
Generate Docs from this repo

### ISSUE THREAD

**Issue by d-koppenhagen** [MelihAltintas/vue3-openlayers#141]
**Is your feature request related to a problem? Please describe.**
Currently keeping the documentation up-to-date means to update the separate repo https://github.com/MelihAltintas/vue3-openlayers-docs after making changes here. This causes the code and documentation to diverge.

**Describe the solution you'd like**
Integrate the documentation Generation (from [here](https://github.com/MelihAltintas/vue3-openlayers-docs)) in this repo.
It would make it easier to update the documentation and keep it in sync with the supported features. Also it will reduce duplicated code for showcases having in both repos right now.

**Comment by mrsimpson** [comment]
@MelihAltintas I had also seen features in the code which didn't make it into the docs (don't quite remember which one it was though). I do think it would help have the docs generated from here to improve consistency.
Any reason not to do that?
