### ISSUE TITLE
DrawInteraction not stylable

### ISSUE THREAD

**Issue by PhilippePinheiroLIST** [MelihAltintas/vue3-openlayers#146]
Documentation says that we can put a Style inside an DrawInteraction (Use it inside ol-feature, ol-vector-layer, ol-interaction-select, ol-interaction-draw, ol-interaction-modify to give custom styles to vector features.)
but DrawInteraction is not "stylable"

To Reproduce : add Style inside a DrawInteraction

**Comment by d-koppenhagen** [comment]
@PhilippePinheiroLIST I created a playground repo for reproduction:
https://stackblitz.com/edit/vue3-openlayers-issue-146?file=src%2Fcomponents%2FTheMap.vue

It seems styling is supported now within an `ol-interaction-draw`.

Please re-open with detailled reproduction steps, when the problem still exists.

Please note: When using the draw interaction for drawing a Point, the style inside is not shown, as directly with the click on the map finished the point draw interaction, so you will see the style thats defined for the displayed features of the vector source.
