### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'val.toLowerCase')

### ISSUE THREAD

**Issue by signmeuptwice** [MelihAltintas/vue3-openlayers#17]
**Describe the bug**
Loading my component I get the following error : TypeError: undefined is not an object (evaluating 'val.toLowerCase')

`[Vue warn]: Failed to resolve async component: function MapData() {
  return Promise.all(/*! import() */[__webpack_require__.e("defaultVendors-node_modules_vue3-openlayers_dist_vue3-openlayers_common_js"), __webpack_require__.e("defaultVendors-node_modules_ol_Object_js-node_modules_ol_has_js-node_modules_ol_proj_js"), __webpack_require__.e("defaultVendors-node_modules_vue3-openlayers_dist_vue3-openlayers_css-node_modules_ol_style_Style_js"), __webpack_require__.e("default-src_vue_component_map_map-data_vue-data_image_png_base64_iVBORw0KGgoAAAANSUhEUgAAABIA-d8f71b")]).then(__webpack_require__.bind(__webpack_require__, /*! ../map/map-data.vue */ "./src/vue/component/map/map-data.vue"));`

**To Reproduce**
I just installed vue3-OpenLayers in my project

**Expected behavior**
no error message

**Desktop (please complete the following information):**
 - OS: OSX latest
 - Browser: All browsers

**Additional context**
I just installed vue3-OpenLayers in my project
using webpack 5

here is my component: 
[gist](https://gist.github.com/signmeuptwice/c244d48b3a479aea78b7d16fd47fa7d0)

**Comment by MelihAltintas** [comment]
Hello, this component was written for vue3. You are using vue2. If you are going to continue with vue2 I recommend the vuelayers library.
