### ISSUE TITLE
ol-interaction-modify sample at vue3openlayers.netlify.app doesn't work properly. It doesn't leave the mode of drawing polygons

### ISSUE THREAD

**Issue by teodorro** [MelihAltintas/vue3-openlayers#186]
An example at https://vue3openlayers.netlify.app/componentsguide/interactions/modify/ doesn't work properly.
How to reproduce:
1. Click the button above the map that change drawing mode to true.
2. Draw a new polygon
3. After a double click polygon will be finished and the drawing mode will be changed to false.
=> However now if you start clicking on the map, you will still be drawing a polygon. Selection won't work, the first you've drawn is selected. Dbl click will only make a new polygon disappear.
![image](https://user-images.githubusercontent.com/14045231/233403451-7b0ef7fe-a5ef-4613-8ef5-4b1e774b5960.png)

**Comment by Oleg72pc** [comment]
Looks like `OlModifyInteraction.vue` has same issue:
sometimes it does not remove old `modify` object from `interactions`, and it stays in modify mode even after `OlModifyInteraction.vue` was unmounted

**Comment by d-koppenhagen** [comment]
Have you tried using the latest `next` release? `npm i vue3-openlayers@next`

**Comment by Oleg72pc** [comment]
it helped, thanks
