### ISSUE TITLE
How to use DragRotateAndZoom interaction of map?

### ISSUE THREAD

**Issue by goforward01** [MelihAltintas/vue3-openlayers#19]
**Describe the bug**
Upgrade to latest version of 0.1.39, and couldn't find any information about using DragRotateAndZoom interaction of map

**To Reproduce**
Just run `npm run serve` in project directory, then use shift key and drag to rotate, the rotation of map never change

**Expected behavior**
Could change the rotation of map by shift+drag

**Comment by MelihAltintas** [comment]
thanks for your request. I added <ol-interaction-dragrotatezoom /> for DragRotateAndZoom interaction. Please update 0.1.40.

props
condition : A function that takes an module:ol/MapBrowserEvent~MapBrowserEvent and returns a boolean to indicate whether that event should be handled. Default is module:ol/events/condition.shiftKeyOnly.
you can get all conditions with 
```
        const conditions = inject('ol-selectconditions')
        const pointerMove= conditions .pointerMove;
```

duration(Number): Animation duration in milliseconds.
