### ISSUE TITLE
Allow ol-style's overrideStyleFunction to return a list of styles; also provide resolution to callback function

### ISSUE THREAD

**Issue by pjreed** [MelihAltintas/vue3-openlayers#191]
The `ol-style` element currently takes an `overrideStyleFunction` attribute, in which you can pass a function that takes a feature and a style as an argument.  It is expected to modify the style in-place in order to set the style for whatever element that `ol-style` is a child of.

This is somewhat limiting because in places where OpenLayers allows you to set a style, it accepts one of a single style object, an array of style objects, or a callback function that is provided a feature and resolution and returns a list of styles.  For example:
https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html#setStyle
https://openlayers.org/en/latest/apidoc/module-ol_Feature-Feature.html#setStyle

Only being able to provide one style per feature or layer is very limiting when drawing complex features.  Lacking the resolution also makes it hard to draw styles that scale based on the map resolution; it's possible to get the resolution from the map and pass it around, but that's inconvenient for an application that is split into multiple components and it already exists in OpenLayers' API.

**Comment by d-koppenhagen** [comment]
@pjreed would you like to contribute?

**Comment by d-koppenhagen** [comment]
Should be solved with [Release 1.0.0-next.8](https://github.com/MelihAltintas/vue3-openlayers/releases/tag/v1.0.0-next.8)
