### ISSUE TITLE
Custom icon on print button

### ISSUE THREAD

**Issue by 1Map** [MelihAltintas/vue3-openlayers#197]
How can I have my own font awesome icon on the ol-control-printdialog and not the default icon?

Currently:

<img width="26" alt="image" src="https://github.com/MelihAltintas/vue3-openlayers/assets/1152458/b2b77ab2-1b22-4546-bd35-e5ff4ae8935c">

What I want:

<img width="28" alt="image" src="https://github.com/MelihAltintas/vue3-openlayers/assets/1152458/04fb4318-ee86-4016-b8da-9707e70f3c03">

**Comment by d-koppenhagen** [comment]
@1Map this should work by setting the `target` attribute. See: https://viglino.github.io/ol-ext/doc/doc-pages/ol.control.PrintDialog.html

If it still doesn't work, please describe the problem in detail and provide a minimal reproduction playground using the following [Stackblitz starter template](https://stackblitz.com/edit/vue3-openlayers-template).
