### ISSUE TITLE
How do I just draw a polygon and add it to a layer?

### ISSUE THREAD

**Issue by iboates** [MelihAltintas/vue3-openlayers#199]
I am struggling a lot just simply drawing a polygon and adding it to a layer.

I have tried reading through this issue: [How to Save/Recover/Program/Add/Delete Features ?](https://github.com/MelihAltintas/vue3-openlayers/issues/24) and to be honest I just find the answers bewildering, any time I try to copy any of the answers into my code, I am told that "source.value.source is undefined", or something else just doesn't work.

This is my code. Forgive me for being naive, but how do I "just get the drawn feature into the features array"? What am I doing wrong?

```
<template>
  <VLayoutItem model-value size="88">
      <div class="ma-4">
          <VBtn
            @click="clear"
            icon="mdi-shape-polygon-plus"
            size="large"
            color="primary"
            elevation="8" />
      </div>
    </VLayoutItem>

  <ol-map
    :loadTilesWhileAnimating="true"
    :loadTilesWhileInteracting="true"
    style="height:95%"
  >
    <ol-view
      ref="view"
      :center="center"
      :rotation="rotation"
      :zoom="zoom"
    />


    <ol-tile-layer>
      <ol-source-osm />
    </ol-tile-layer>

    <ol-vector-layer>
      <ol-source-vector
        ref="source"
        :features="features"
      >
        <ol-interaction-draw
          v-if="draw"
          type="Polygon"
          @drawend="drawEnd"
        >
        </ol-interaction-draw>
        <ol-interaction-modify
          v-if="modify"
        >
          </ol-interaction-modify>
      </ol-source-vector>

      <ol-style>
        <ol-style-stroke color="red" :width="2"></ol-style-stroke>
      </ol-style>
    </ol-vector-layer>
  </ol-map>
</template>
  
  <script>
  import { ref, inject } from "vue";
  export default {
    setup() {
      const center = ref([40, 40]);
      const zoom = ref(8);
      const rotation = ref(0);
      return {
        center,
        zoom,
        rotation,
      };
    },
    data() {
        return {
            draw: true,
            modify: false,
            features: []
        }
    },
    props: {
        drawnFeature: null
    },
    methods: {
        clear() {
            this.draw = true;
            this.modify = false;
        },
        drawEnd(e) {
          this.draw = false;
          this.modify = true;
          console.log(e);
          this.features.push(/* How do I push the feature into the features array? */)
        },
    },
  };
  </script>
```

**Comment by dejvlamm** [comment]
First of all, you dont need the features array.
The draw interaction is placed <inside> a vector source so the drawn polygon will just be added to that source.
So just removed :features="features" and it should work.

If you for some other reason want to access the feature on drawEnd, you can simply grab it from the event.

In your case, the feature is in the "e" event:
```
drawEnd(e) {
    this.draw = false;
    this.modify = true;
    console.log(e.feature); // Here is the feature you just drew
},
```

**Comment by d-koppenhagen** [comment]
@iboates could you solve your problem? If not: can you provide a minimal reproduction playground using the following [Stackblitz starter template](https://stackblitz.com/edit/vue3-openlayers-template)

**Comment by d-koppenhagen** [comment]
I will close this issue for now. Feel free to re-open it if the problem still exists and provide the requested information (see comment before).
