### ISSUE TITLE
select-interaction filter prop

### ISSUE THREAD

**Issue by akc4** [MelihAltintas/vue3-openlayers#2]
I get this error when passing the `filter` prop on `ol-interaction-select` component.

`
Extraneous non-props attributes (filter) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
`

```
<ol-interaction-select @select="featureSelected" :condition="data.selectCondition" :filter="filterFunc"></ol-interaction-select>
```

**Comment by MelihAltintas** [comment]
Which version are you using? When I tested 0.1.23, I did not see such a problem.

**Comment by akc4** [comment]
You are right I just updated to 0.1.24 and it works. I was on "^0.1.21".

Thank you
