### ISSUE TITLE
Missing Bing Image preview in MapControls.LayerSwitcherImageControl

### ISSUE THREAD

**Issue by 1Map** [MelihAltintas/vue3-openlayers#200]
**Describe the bug**
The image preview is missing in MapControls.LayerSwitcherImageControl for a Bing Maps Source.

**To Reproduce**
Add Bing Layer with Sources.SourceBingMaps and also add MapControls.LayerSwitcherImageControl. Preview image not showing.

**Expected behavior**
Suppose to see preview image

**Comment by d-koppenhagen** [comment]
I added some documentation. Please define the `imagerySet` on `ol-source-bing`. This should fix your issue. I added this example also to the MapControls demo.
