### ISSUE TITLE
Missing Stamen Toner Layer Sources

### ISSUE THREAD

**Issue by 1Map** [MelihAltintas/vue3-openlayers#201]
**Describe the bug**
Missing Stamen Toner as a Layer Source

[OL Link to Stamen Toner Source](https://openlayers.org/en/latest/apidoc/module-ol_source_Stamen-Stamen.html)

**Comment by d-koppenhagen** [comment]
It has been implemented with [v1.0.0-next.1](https://github.com/MelihAltintas/vue3-openlayers/releases/tag/v1.0.0-next.1).
