### ISSUE TITLE
Error installing. missing "./styles.css" specifier in "vue3-openlayers" package

### ISSUE THREAD

**Issue by pbooox** [MelihAltintas/vue3-openlayers#202]
Hi there, i'm trying to start using the package but it isn't working. is a new vue 3.3.4 project

**Screenshots**
<img width="811" alt="Screenshot 2023-06-16 at 09 47 17" src="https://github.com/MelihAltintas/vue3-openlayers/assets/45060148/2942a7ef-82b7-41ac-bfa2-964a9cf1cb85">
[](url)
<img width="374" alt="image" src="https://github.com/MelihAltintas/vue3-openlayers/assets/45060148/500015d3-1399-471c-9d0e-6c1f8fb587b7">

**Comment by d-koppenhagen** [comment]
Sorry, docs were already on the `next` channel. please use `import "vue3-openlayers/dist/vue3-openlayers.css";` or update to the latest version `npm i vue3-openlayers@next`
