### ISSUE TITLE
ol-source Event handler example

### ISSUE THREAD

**Issue by DanRamage** [MelihAltintas/vue3-openlayers#208]
**Is your feature request related to a problem? Please describe.**
I am unable to get handlers for tileloadstart and tileloadend to work on an ol-source-xyz. I was hoping to get a working example.

For reference this is how I have the component declared:
`

                <ol-tile-layer ref="google_layer">
                    <ol-source-xyz ref="google_layer_source" :url="current_layer_url"
                                   @tileloadstart="tile_load_start" @tileloadend="tile_load_end">
                    </ol-source-xyz>
                </ol-tile-layer>

`

`
        methods: {
            tile_load_start(evt) {
              evt;
              this.tiles_load_count += 1;
              console.debug("tile_load_start started, count: " + this.tiles_load_count);
            },
            tile_load_end(evt) {
              evt;
              this.tiles_load_count -= 1;
              console.debug("tile_load_end started, count: " + this.tiles_load_count);
              if(this.tiles_load_count <= 0)
              {
                this.tiles_load_finished = true;
              }
            }
        }

`
The handlers never get called.

**Comment by d-koppenhagen** [comment]
Can you please provide the version of `vue3-openlayers` you are using?

**Comment by kankantian** [comment]
I come across the same problem when I add tileLoadFunction to ol-source-xyz. It seems that there is no way to origin openlayer API

**Comment by d-koppenhagen** [comment]
Same here: What version are you using?
it should work with the latest next release [v1.0.0-next.3](https://github.com/MelihAltintas/vue3-openlayers/releases/tag/v1.0.0-next.3)

**Comment by DanRamage** [comment]
I'm using version: 0.4.0.

**Comment by d-koppenhagen** [comment]
Please try to update and tell me if the problem still exists.

**Comment by DanRamage** [comment]
Events tileloadstart and tileloadend are getting emitted now. I am seeing the following warning in Firefox debugger:
`
[Vue warn]: Component emitted event "tileloadend" but it is neither declared in the emits option nor as an "onTileloadend" prop.
`

**Comment by d-koppenhagen** [comment]
yes. It's cause I wanted to find a way to pass-through events without to re-define each one from scratch. So it works currently but the downside are the log. I will probably raise an Issue für Vue itself with a feature request. Anyways: It should work. I will close this issue.

**Comment by DanRamage** [comment]
It appears the latest version, 1.2.0,  still has this issue.
