### ISSUE TITLE
Easier way to handle errors from `ol-geolocation`

### ISSUE THREAD

**Issue by manusaurio** [MelihAltintas/vue3-openlayers#209]
**Is your feature request related to a problem? Please describe.**
It's just a minor inconvenience. The library is great and allows doing many things effortlessly, so I think it'd be great if there was a way to handle geolocation errors in some way directly offered by the vue3-openlayers API. I don't think doing something like warning the user geolocation is needed is that odd (or just to make sure they know... maybe they didn't grant the permission and blocked it on the site without realizing.)

**Describe the solution you'd like**
An emit would be nice, although I'm not sure if this is an strange pattern for this case. Something like `@onError=` maybe?

**Describe alternatives you've considered**
Right now I'm just using a template ref in `ol-geolocation` and using `myRef.value.geoLoc.on('error', ...)` after mounting the component. It looks a bit brittle.

**Comment by d-koppenhagen** [comment]
I agree! I was refactor some other components the last days to be able to pass-through `on` events from openlayers. I have it on my list :)

**Comment by d-koppenhagen** [comment]
Done. Published with version [v1.0.0-next.7](https://github.com/MelihAltintas/vue3-openlayers/releases/tag/v1.0.0-next.7).
Please have a look at the breaking changes.
