### ISSUE TITLE
`Failed to resolve component: ol-view` with basic doc example: How to import locally instead of globally ?

### ISSUE THREAD

**Issue by signmeuptwice** [MelihAltintas/vue3-openlayers#21]
I have this very basic component below that gives me error:

`Failed to resolve component: ol-view`

I do not understand how to import vue3-openLayers properly. I used code from the official doc. It seems that the global imports are missing but I want to use in my component only. How do I import and reference inside my component.

The doc is not helping from what I can tell.

here is my full component

` <template>

    <ol-map :loadTilesWhileAnimating="true" :loadTilesWhileInteracting="true" style="height:400px">

    <ol-view ref="view" :center="center" :rotation="rotation" :zoom="zoom"
             :projection="projection" />

    <ol-tile-layer>
      <ol-source-osm />
    </ol-tile-layer>

    </ol-map>

    </template>

    <script>
    import {ref} from 'vue'

    export default {
    setup() {
      const center = ref([40, 40])
      const projection = ref('EPSG:4326')
      const zoom = ref(8)
      const rotation = ref(0)
      return {
        center,
        projection,
        zoom,
        rotation
      }
      },
     }
     </script>`

**Comment by blackawn** [comment]
How did you import it?

**Comment by woxfer** [comment]
how did you fix this issue ?

**Comment by paulterinho** [comment]
@akbasferhat Probably not what you are looking for (my guess is that you were looking for how to do this locally), but I was running into this because I didn't init it globally (https://vue3openlayers.netlify.app/get-started.html#usage), posting this for future newbies like myself that stumble into this link.
