### ISSUE TITLE
Contribution guide is useless in its current form

### ISSUE THREAD

**Issue by christophfriedrich** [MelihAltintas/vue3-openlayers#217]
**Situation**
I want to contribute to this project. As a good contributor, I check out [CONTRIBUTING.md](https://github.com/MelihAltintas/vue3-openlayers/blob/main/CONTRIBUTING.md) before doing so.

**Expected content**
Concise information on how to contribute to this repository, e.g. "set up your dev env like this", "keep code style like that", "always create PRs against branch X".

**Actual content**
Lots of blabla that doesn't help me much and is mostly not even applicable to this project.

**Cause**
Two years ago, the file was just copied from the github/docs repo and never adapted.

**Possible solutions**
1. Adapt the text, or
2. Delete the file.

**Comment by d-koppenhagen** [comment]
Thanks @christophfriedrich . Yes the guide should be updated! However: it's more documentation but not a bug within the lib itself.
