### ISSUE TITLE
[Warning] No map visible because the map container's width or height are 0

### ISSUE THREAD

**Issue by signmeuptwice** [MelihAltintas/vue3-openlayers#22]
from doc example, inserting the following component

`    <ol-overviewmap-control><ol-tile-layer><ol-source-osm /></ol-tile-layer></ol-overviewmap-control>`

gives error

`[Warning] No map visible because the map container's width or height are 0.`

I imported 

`import 'vue3-openlayers/dist/vue3-openlayers.css'`

tested in my project and with fresh project from latest source

**Comment by akc4** [comment]
do you have a height on your map container? `<ol-map style="height:400px">`

**Comment by signmeuptwice** [comment]
no that did not solve the issue.

**Comment by MelihAltintas** [comment]
this is overview map control warning bug. I solved the problem with 0.1.44 please update it. thanks for your bug report.

**Comment by TaylorGit9** [comment]
Hi @signmeuptwice ,
I had the same issue and I fixed a min-width and min-height with also width and height :

_<style>
  #map {
    width: 100%; height: 100%;
    min-width: 100vh; min-height: 80vh;
  }
</style>_

It solved the problem.

**Comment by johndeighan** [comment]
I'm getting this warning with OpenLayers 7.4.0, even though I've set the container div to have a width and height via CSS. Then, the map appears, but the copyright message is incorrectly placed. Here is my web page:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<title>My First Parcel App</title>
	<style>
		#map {
			width: 800px;
			height: 600px;
			}
	</style>
</head>
<body>

<h1>Open Layers Tutorial</h1>

<div id="map"></div>

<!-- --------------------------------------------- -->
<script type="module">

import View from 'ol/View.js';
import Map from 'ol/Map.js';
import OSM from 'ol/source/OSM.js';
import TileLayer from 'ol/layer/Tile.js';
import {defaults} from 'ol/control/defaults';
import FullScreen from 'ol/control/FullScreen.js';
import MousePosition from 'ol/control/MousePosition.js';
import OverviewMap from 'ol/control/OverviewMap.js';

let targetElem = document.getElementById('map');

let view = new View({
	center: [0,0],
	zoom: 2,
	minZoom: 2,
	maxZoom: 6,
	enableRotation: true,
	rotation: 0,
	});
let map = new Map({
	target: targetElem,
	view,
	layers: [
		new TileLayer({
			source: new OSM()
			})
		],
	keyboardEventTarget: document,
	controls: defaults().extend([
		new FullScreen(),
		new MousePosition(),
		new OverviewMap(),
		]),
	});
console.log("Working");

</script>

</body>
</html>

```
Though I doubt it's relevant, I'm using parcel for my dev server since it supports hot reloading. I previously got the very same behavior when using SvelteKit, but there's a lot of complexity there so I wanted to do the same with a simple web server. FYI, I install the Open Layers library using `npm install ol`
