### ISSUE TITLE
Can add Baidu and Amap tiles

### ISSUE THREAD

**Issue by smilemouse** [MelihAltintas/vue3-openlayers#220]
Whether there is a plan to implement

**Comment by d-koppenhagen** [comment]
Hey, it should be possible to realize it with an XYZ source plus sing a custom projection and load function.
See: https://github.com/openlayers/openlayers/issues/3522

To implement this as special feature components I need more insights and source for both: Baidu, Amap. Is there a specification / example code? Unfortunately lot's of the source I found seems not to exist in English language.

Do you may want to contribute @smilemouse ?

**Comment by d-koppenhagen** [comment]
Since there was no response, I will close this issue for now.

**Comment by dbauszus-glx** [comment]
I am trying to add an autonavi xyz-tiles layer to Openlayers 8.1 but are unable to workout the shift between web-mercator (3857) and the amap web-mercator with [GCJ-02](https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#GCJ-02) datum. I followed @tschaub example referenced in #3522 but didn't get anywhere.

I put together a codepen for this if you would like to have a look.
