### ISSUE TITLE
Missing Tests

### ISSUE THREAD

**Issue by chrstnbwnkl** [MelihAltintas/vue3-openlayers#222]
I have recently written a number of `ol` specific vuejs components for a client and taken some inspiration from this library. I have noticed that the components in this repo are hardly tested. Is there a specific reason? I have written some tests for my library, so if you'd like I can use some of my learnings to contribute some basic unit testing (and possibly integration testing with a tool like `cypress`)  back into your repo :-)

**Comment by d-koppenhagen** [comment]
Hey @chrstnbwnkl I totally agree: this project should be better tested using unit and integration tests.
it would be great to take advantage of your learnings. So please, send us a PR with your test setup.

**Comment by chrstnbwnkl** [comment]
Update: I have started working on this, but didn't have too much time on my hands yet. I'll probably split it up in two PR's: one for unit testing single components using `vitest` and another one for integration testing with nesting multiple components using cypress. I'll start with the unit test, and I'll probably end up only testing a couple of components, since there's just so many :sweat_smile: (you guys did a great job supporting a lot of features hahah)

**Comment by d-koppenhagen** [comment]
That would be awesome. If the first tests landed as blueprint, we can add further step-by-step. That should be straightforward.

**Comment by d-koppenhagen** [comment]
@chrstnbwnkl is there anything I can already pick?

**Comment by d-koppenhagen** [comment]
An idea from my site: with cypress or playwright, it should be simple easy to create snapshot tests for visual regression testing (DOM snapshots doesn't make sense for most use cases as Features will be drawn on a canvas).

Iterating over the vitepress configs entries should give us the paths and titles for the component and should allow is to write a single loop test which covers all.
The test could search for the map element and record/compare a screenshot of this one.

**Comment by chrstnbwnkl** [comment]
Sorry for the inactivity here, a long vacation stood in the way :sweat_smile: Let me polish up the unit tests I have so far for now. I haven't considered visual regression testing yet, but I like the idea (at least for non-remote feature layers, maybe not so robust for testing e.g. the default OSM tile layer)
