### ISSUE TITLE
Can i disable mouse wheel on mouse over map?

### ISSUE THREAD

**Issue by 4got** [MelihAltintas/vue3-openlayers#225]
How to disable mouse wheel?
Prevent it from zoom?

**Comment by d-koppenhagen** [comment]
This should help:

https://gis.stackexchange.com/questions/136782/how-do-i-disable-mouse-scroll-zoom-in-openlayers-3/136786#136786

You can you the API of `ol-map`

**Comment by d-koppenhagen** [comment]
Okay, just checked the source code. You can simply set the `mouseWheelZoom` prop to `false`:

```html
<ol-map :mouseWheelZoom="false" style="height: 400px">
```

I will add it to the docs
