### ISSUE TITLE
Add vector tile layer

### ISSUE THREAD

**Issue by MichalPoty** [MelihAltintas/vue3-openlayers#228]
I have tried to add a vector tile layer (in .pbf format), but unsuccessfully, because there is no component for it. In the [VueLayers](https://vuelayers.github.io/#/docs/component/vector-tile-layer) version (Vue 2) there are `vl-layer-vector-tile` and `vl-source-vector-tile` components, but they are missing here. 

Is there a reason for this not being implemented yet?

**Comment by d-koppenhagen** [comment]
Sure it can be added.
Do you like to contribute? It should be straight-forward, comparing with the other source / layers.

Do you have a link for a public pbf source or one with demo credentials?

**Comment by MichalPoty** [comment]
Great,
Yes, I'd like to contribute, but I don't have much experience with it yet, so I might need some help.

Here should be the public pbf source from the official [OL examples](https://openlayers.org/en/latest/examples/vector-tile-info.html): https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/tile/{z}/{y}/{x}.pbf

**Comment by okame** [comment]
You'll excuse me from the side.
I added "ol-vector-tile-layer" component just now.
Can I contribute this works?
(I don't udpate documents yet.)

https://github.com/okame/vue3-openlayers/commit/73e0932b472629199b8f3d1794482f81375b46ba

**Comment by d-koppenhagen** [comment]
Just released version 1.2.0 with this feature added.
