### ISSUE TITLE
Property 'refresh' does not exist on type 'Map'

### ISSUE THREAD

**Issue by chrstnbwnkl** [MelihAltintas/vue3-openlayers#231]
**Describe the bug**
The `OlMap` component exposes a `refresh` function that calls a `refresh` method on the map instance. However, I don't  seem to find such a method on the `ol.Map` class. 

**Affected version(s)**

Please run `npm list --depth=0 vue vue3-openlayers ol ol-ext ol-contextmenu` and paste the output below:

```
├── ol-contextmenu@5.2.1
├── ol-ext@4.0.8
├── ol@7.4.0
└── vue@3.3.4

```

**To Reproduce**

Simply install the project locally and inspect the `OlMap` component in the IDE of your choice. TypeScript should be complaining.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 14]
- OS: [e.g. iOS 16.15.1]

**Additional context**

**Comment by chrstnbwnkl** [comment]
Ah, I just realized this is just to make it backwards compatible with older `ol` versions, nevermind. Maybe this could be briefly added to the "Get started" section in the docs? Since there, it says that `^7.4.0` is required.

**Comment by d-koppenhagen** [comment]
Thanks for reporting @chrstnbwnkl . Indeed it was simply not removed in this lib.
I removed this methods and other methodas and props that aren't compatible with OpenLayers 7.x.x.
See 81c6d00.
