### ISSUE TITLE
Toggle Controls do not work

### ISSUE THREAD

**Issue by ierror** [MelihAltintas/vue3-openlayers#232]
**Describe the bug**
Toggle Controls do not work
```
<ol-control-bar> 
  <ol-toggle-control ...
```

**1.2.0**

Please run `npm list --depth=0 vue vue3-openlayers ol ol-ext ol-contextmenu` and paste the output below:

```
├── ol-contextmenu@5.2.1 -> ./node_modules/.pnpm/ol-contextmenu@5.2.1_ol@7.4.0/node_modules/ol-contextmenu
├── ol-ext@4.0.10 -> ./node_modules/.pnpm/ol-ext@4.0.10_ol@7.4.0/node_modules/ol-ext
├── ol@7.4.0 -> ./node_modules/.pnpm/ol@7.4.0/node_modules/ol
├── vue@3.3.4 -> ./node_modules/.pnpm/vue@3.3.4/node_modules/vue
└── vue3-openlayers@1.2.0 -> ./node_modules/.pnpm/vue3-openlayers@1.2.0_ol-contextmenu@5.2.1_ol-ext@4.0.10_ol@7.4.0_vue@3.3.4/node_modules/vue3-openlayers

```

**To Reproduce**

1. Go to https://vue3openlayers.netlify.app/componentsguide/mapcontrols/
2. Activate `ol-toggle-control`
3. See error

**Expected behavior**
The toggle switch is displayed in the correct position and works "on click".

**Screenshots**
<img width="1071" alt="Screenshot 2023-07-28 at 13 51 09" src="https://github.com/MelihAltintas/vue3-openlayers/assets/844375/3cf60b01-1516-47fd-b12d-96eaacb518d0">

**Comment by d-koppenhagen** [comment]
It's not a bug. Events and props are passed 1:1 from `ol-ext`. Please refer to the original docs.
https://viglino.github.io/ol-ext/doc/doc-pages/ol.control.Toggle.html

You have to pass a `onToggle` function which receives a `true` or `false` on toggle:

```html
 <ol-toggle-control :onToggle="console.log" />
```

I added it to the docs example:
b01ef6435011f5cb6d55752349ef30b3db2607df
