### ISSUE TITLE
How to Save/Recover/Program/Add/Delete Features ?

### ISSUE THREAD

**Issue by signmeuptwice** [MelihAltintas/vue3-openlayers#24]
Not really a bug but I need advice from the developpers because I am completely lost on the logic behind how to deal with feature states

the doc is not clear; at least for me.

I have this template

     <ol-interaction-select @select="featureSelected" :condition="selectCondition" :features="selectedFeatures">
        <ol-style>
          <ol-style-stroke :color="'red'" :width="2"></ol-style-stroke>
          <ol-style-fill :color="`rgba(255, 0, 0, 0.4)`"></ol-style-fill>
        </ol-style>
      </ol-interaction-select>
    <ol-source-vector :projection="projection">
       <ol-interaction-modify v-if="modifyEnabled" :features="selectedFeatures" @modifyend="modifyend"></ol-interaction-modify>
       <ol-interaction-draw v-if="drawEnable" :type="drawType" @drawend="drawend"></ol-interaction-draw>
    </ol-source-vector>

and the logic:

    import {Collection} from "ol"
    setup(){
           const selectedFeatures = ref(new Collection())
           let newFeatures = ref([])

           const drawend = (event) => {
              newFeatures.value.push({type:event.target.type_, coordinates:event.target.sketchCoords_})
              modifyEnabled.value = true
              drawEnable.value = false
              emit()
           }
           const modifyend = (event) => {
               // how to know which feature I am editing and how to get the new value ?
               emit()
            }
            function featureSelected(event) {
              const feature = event.target.getFeatures()
              selectedFeatures.value = event.target.getFeatures()
              if(feature.array_ && feature.array_.length) {
                 let coordinates = null
                 if(feature.array_[0].values_.geometries && feature.array_[0].values_.geometries.length) {
                   coordinates = feature.array_[0].values_.geometries[0].flatCoordinates
                 } else if(feature.array_[0].values_.geometry) {
                   coordinates = feature.array_[0].values_.geometry.flatCoordinates
                 }
                console.log(coordinates)
            }
        }
    }

when I select I get the new `coordinates` with `featureSelected` but that seems cumbersome because I have to dig down into the object and there is no real relation between what I am editing and my data because `newFeatures` is not being updated.

`selectedFeatures` and `newFeatures` have different types so I need to translate one to the other and vice versa ?

Ideally everything should be sharing a single reactive value/format somewhere between the collection and the modified one but they are not linked/bridged ?? Ideally I would just like to put `newFeatures` in the modify component but I need to track `selectedFeature` instead and then copy values back to my `newFeatures` ? 

In `newFeatures` I have a collection of simple data that has no reference to the dom like `[{type:'Point',coordinates:[3,2,5]}]`
in `selectedFeatures` I have a complex object so How am I supposed to keep references between both objects?

so I can get new values from `console.log(coordinates)` but what am I supposed to do with these ? How do I update my `newFeatures` array? is there no simple feature getter and setters ? 

Clearly there must be something I am missing because I can't even extract feature type like LineString, circle, etc... from the modify event object.

in `featureSelected` I need to do `selectedFeatures.value = event.target.getFeatures()` and in `drawend` I have to do `selectedFeatures.value.push(event.feature)`. What is the reason ?

or I could do without `newFeatures` if there is a way to get all current features from ol-interaction-draw component for export? but in which format to store in database so I can re-edit them later ?

Could you clarify for me? Sorry but I have been on this for 2 days now.

Full code [https://gist.github.com/signmeuptwice/c45085e64e09828bc6f3bc81635fdb9e](url)

**Comment by MelihAltintas** [comment]
Hello,

I don't understand why do you use newFeatures. whenever you want you can easily access all features in the source with ref.

```
    <ol-vector-layer>
        <ol-source-vector **ref="source"**>

            <ol-interaction-modify v-if="drawEnable" @modifyend="modifyend" @modifystart="modifystart">

            </ol-interaction-modify>

            <ol-interaction-draw v-if="drawEnable" :type="drawType" @drawend="drawend" @drawstart="drawstart">

            </ol-interaction-draw>

            <ol-interaction-snap v-if="drawEnable" />

        </ol-source-vector>

    </ol-vector-layer>
```
in setup :

```
**const source = ref(null);**
// in drawend or modifyend access all features with this line =
**source.value.source.getFeatures()**
return {
    source
}
```

**Comment by signmeuptwice** [comment]
Thank you for the suggestion, I updated my gist with latest code and I gave up on `newFeatures`

I tried your solution but I still do not understand

I don't know if I found a bug but my `console.log(features)` at in `drawEnd` if not showing correct values:
I draw a point and it shows empty
I draw a circle and it shows the point
I draw something else and it shows the circle
and so on ...

So assuming that there is no bug

when I do `source.value.source.getFeatures()` I get a complex object again.
How am I supposed to store it in my database ? Then how do I get the features back ? Can I use `source.value.source.setFeatures(myFeaturesFromDatabase)`

**Comment by MelihAltintas** [comment]
this is not a bug. The drawend event does not guarantee that the feature is added to the source. You can watch this like that (not inside drawend event): 

```
        onMounted(() => {
            source.value.source.on('addfeature', function () {
                console.log(source.value.source.getFeatures())
            })

            source.value.source.on('changefeature', function () {
                console.log(source.value.source.getFeatures())
            })
        })
```

How you want to keep the features in the database depends on your architecture.  I hold features as  geojson string.

for info: https://gis.stackexchange.com/questions/179907/openlayers-3-geojson-save-and-load
on write you should use writeFeatures method of GeoJSON
on load you should use readFeatures method of GeoJSON and than you should load this features to map source.value.source.setFeatures(myFeaturesFromDatabase)

**Comment by signmeuptwice** [comment]
Star indeed :)
Thanks for the infos; I will look at this tomorrow; looks promising
Glad to hear you are trying to streamline this; the more abstract the getters and setters the better imo; we always have the vanilla option if we want too.
I opened a new feature request on this matter.

**Comment by signmeuptwice** [comment]
That seems to be working; haven't tried saving to db yet but I think I will be able to get this working with your previous comment.

but I now run into another issue

sorry for all the questions but as a new user who is not very familiar with vanilla OL. I hope my journey will help you improve this already fantastic component for new users.

I have a `selectedFeatures` but would like to extract the currently highlighted/selected feature to remove it
I tried this code but it seems to break ol internally so I am guessing there must be a getter in `selectedFeatures` ?

   `const deleteSelectedFeature = () => {
      const feature = selectedFeatures.value
      if(feature){source.value.source.removeFeature(feature.array_[0])}
    }`

Thank you for your time

**Comment by signmeuptwice** [comment]
I tried this code as suggested but it fails at `setFeatures()`. I looked at `source.value` and there is no `source` object

          const reader = new format.GeoJSON();
          const features = reader.readFeatures(props.locationData.location.drawnFeatures);
          console.log(features) // ok here
          source.value.source.setFeatures(features) // undefined source

**Comment by signmeuptwice** [comment]
I managed to import features like this .. Is this the right way ? seems to work... No need for setFeatures ?

        <ol-source-vector ref="sourceVectorNew" :projection="projection" :features="existingFeatures">

         const features = reader.readFeatures(props.locationData.location.drawnFeatures);
         existingFeatures.value = features

**Comment by MelihAltintas** [comment]
Yes this way is correct. Openlayers vectorsource does not contain SetFeatures method i am sorry. It has a addFeatures method :). But your way is good don't change it. You can easily see all methods in doc of openlayers
https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html
