### ISSUE TITLE
Getter / Setter for Features and or entire State

### ISSUE THREAD

**Issue by signmeuptwice** [MelihAltintas/vue3-openlayers#25]
**Is your feature request related to a problem? Please describe.**
Managing features easily so we can export them in a classic es6 object format to store in database and reuse later
This is basically abstracting OL

we can expand this to a complete object of the map state

Would be super useful for beginners

**Describe the solution you'd like**
something like 
`this.$ref.map.getFeatures()`  
`this.$ref.map.removeFeatures()`
`this.$ref.map.addFeatures()`
`this.$ref.map.setFeatures()` 

`this.$ref.map.getState()`
`this.$ref.map.setState()`

**Comment by MelihAltintas** [comment]
Already answered #24
