### ISSUE TITLE
"installed!" displayed in the console

### ISSUE THREAD

**Issue by Ciriak** [MelihAltintas/vue3-openlayers#254]
**Describe the bug**
"installed !" is displayed in the console since the 2.0.0 release
![image](https://github.com/MelihAltintas/vue3-openlayers/assets/9463585/b5321231-d70f-4443-ac6f-c1c2dded415e)

**Affected version(s)**

2.0.0

**To Reproduce**

Just use a component that uses vue3-openlayer

**Expected behavior**
Nothing should be printed at all

Nothing critical of course, but this is a bit annoying

**Comment by d-koppenhagen** [comment]
This looks strange. I couldn't find any log like this in the source in version 2.0.0. Can you cleanup your node_modules / remove this lib and install it again?
