### ISSUE TITLE
OlZoomToExtentControl

### ISSUE THREAD

**Issue by mikehsieh0305** [MelihAltintas/vue3-openlayers#255]
<template
  <ol-zoomtoextent-control
      :extent="extent"
      :label="label"
      :tipLabel="tipLabel"
    /

/template>

<script>
import { ref } from "vue";

export default {
  name: "OlZoomToExtentControl",
  setup() {
    const extent = ref([115.835, 21.269, 117.023, 20.466]);
    const label = ref("R");
    const tipLabel = ref("reset center");
    
    return {
      extent,
      label,
      tipLabel,
    };
  },
};
</script>
<img width="1382" alt="截圖 2023-09-22 上午10 43 05" src="https://github.com/MelihAltintas/vue3-openlayers/assets/125983168/1081cac2-abf0-4a87-9236-abe222190fde">

**Comment by d-koppenhagen** [comment]
Sorry but this issue is not reproducible. The component form your example does not have any template but only exported refs.
Furthermore I would ask you to add some description what exactly doesn't work?
This issue title should be more precisely.
Can you please provide information about the installed version of OpenLayers and vue3-openlayers as well?

**Comment by mikehsieh0305** [comment]
> Sorry but this issue is not reproducible. The component form your example does not have any template but only exported refs. Furthermore I would ask you to add some description what exactly doesn't work? This issue title should be more precisely. Can you please provide information about the installed version of OpenLayers and vue3-openlayers as well?

sorry i update it

**Comment by d-koppenhagen** [comment]
How are you using this component? It must be a child of `ol-map`.

**Comment by mikehsieh0305** [comment]
> How are you using this component? It must be a child of `ol-map`.

<template
  <ol-map
    :loadTilesWhileAnimating="true"
    :loadTilesWhileInteracting="true"
    style="width: 100%; height: 100vh"
  >
    <ol-view
      ref="view"
      :center="center"
      :rotation="rotation"
      :zoom="zoom"
      :projection="projection"
      :maxZoom="maxZoom"
      :minZoom="minZoom"
    />

    <ol-tile-layer ref="taiwanLayer" title="taiwanLayer">
      <ol-source-xyz
        url="https://wmts.nlsc.gov.tw/wmts/EMAP/default/GoogleMapsCompatible/{z}/{y}/{x}/"
      />
    </ol-tile-layer>
    
    <OlContextMenu />
    <OlPrintDialogControl />
    <OlZoomToExtentControl />
  </ol-map>
/template>

<script>
import { ref, inject } from "vue";
import OlContextMenu from "@/components/mapControls/OlContextMenu.vue";
import OlPrintDialogControl from "@/components/mapControls/OlPrintDialogControl";
import OlZoomToExtentControl from "@/components/mapControls/OlZoomToExtentControl";

export default {
  components: {
    OlContextMenu,
    OlPrintDialogControl,
    OlZoomToExtentControl,
  },
  setup() {
    const center = ref([113.44175, 13.3218392]);
    const projection = ref("EPSG:4326");
    const zoom = ref(6);
    const maxZoom = ref(18);
    const minZoom = ref(3);
    const rotation = ref(0);

    const format = inject("ol-format");
    const geoJson = new format.GeoJSON();

    return {
      center,
      projection,
      zoom,
      maxZoom,
      minZoom,
      rotation,
      geoJson,
    };
  },
};
</script>

**Comment by d-koppenhagen** [comment]
Please @mikehsieh0305: this code is veeeeery hard to read. It's half destroyed and half formatted. It makes an investigation pretty hard.

**Comment by d-koppenhagen** [comment]
I will close this issue as it's not clearly described. Please refer to my comments before and re-raise an issue which makes it easy to reproduce an error and to investigate.
