### ISSUE TITLE
autoPan give error

### ISSUE THREAD

**Issue by Kevinrp22** [MelihAltintas/vue3-openlayers#257]
I have the same problem than issue #92 @d-koppenhagen  I have tried your example and it seems to work because the 'autopan' prop should be 'autoPan', if you change it the error does appear.

![Captura de pantalla 2023-09-14 125024](https://github.com/MelihAltintas/vue3-openlayers/assets/47866787/1e4fc5be-10f6-4698-ae25-f0fb3723c188)

**Comment by xxxfengsu** [comment]
it's still error
