### ISSUE TITLE
automatic reprojection of a source

### ISSUE THREAD

**Issue by marcomilone** [MelihAltintas/vue3-openlayers#258]
Hello everybody 👋,

As I understand, and I possibly be wrong, doesn't exists the way to easily reproject a source.
With "easily" I mean with vue-openlayers, without importing functions from ol.

I think the code attached should do the reprojection (and it does nothing in my application).

vue-openlayers is so easy to use: the fact I'm struggling to reproject a source on the fly sounds strange to me.

I mean, I'll like to keep a complete layer "transformed on-the-fly" and the transformation should listen to the source, for changes

The "goal" is not to reproject a single static point.

```html
<ol-map>

  <ol-view :projection="'EPSG:3857'" />

  <ol-tile-layer>
    <ol-source-osm /><!-- implicit EPSG:3857 -->
  </ol-tile-layer>

  <ol-vector-layer :zIndex="2" projection="EPSG:4326">
      <ol-source-vector  >
          <ol-feature ref="positionFeature">
              <ol-geom-point :coordinates="locationStore.coordinates"></ol-geom-point>
              <ol-style>
                  <ol-style-icon :src="geolocationIcon" />
              </ol-style>
          </ol-feature>
      </ol-source-vector>
  </ol-vector-layer>

  <ol-vector-layer id="this_layer_also">
    <ol-source-vector projection="EPSG:4326" :url="url" :format="geoJson" /> 
  </ol-vector-layer>


  <ol-tile-layer projection="EPSG:32632" >
    <ol-source-xyz :url="tileLayer.url" />
  </ol-tile-layer>

</ol-map>
```

this could be achievable with a custom attribute like:

```
   auto-project-to-view="true" // default false
```

```html
<ol-map>

  <ol-view :projection="'EPSG:3857'" />

  <ol-tile-layer>
    <ol-source-osm /><!-- implicit EPSG:3857 -->
  </ol-tile-layer>

  <ol-tile-layer auto-project-to-view="true">
    <ol-source-xyz :url="tileLayer.url" />
  </ol-tile-layer>

</ol-map>
```

This should work on any kind of source. 👀

**Comment by wendellwt** [comment]
This sounds great.  Where is it?  I didn't find this feature in main; is it in a branch?
If not, is the alternative to manually do the reprojection within a `loader` function as described [here](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html)?

**Comment by marcomilone** [comment]
Hi,the fact was that I don't yet (but I'm going to) understand if the reprojection is happening for every source type (tms, xyz, url-geojson, vector/:features .

view has a projection

layers have a source

**Comment by marcomilone** [comment]
Hi,

the fact is that I cannot understand completely from docs.
I should read more about openlayers and vue-openlayers.

I don't (but I'm going to) understand if the automatic re-projection already happens for every layer/source type

- tms
- xyz
- vector geojson with url
- vector with :features 

view has a projection

layers have a source, and a projection

So I opened the issue and closed with shame (because I need to study more)

I'm baking an application that could change main view projection on the and show sources with different projections fly and I have to study more the library (this ⭐️ awesome library)

BTW the function you are pointing at seems the right one to apply.

Thanks

**Comment by wendellwt** [comment]
Thank you for the explanation.  However, I think my problem all along was with reprojection of vector tiles.

Is there an example of ol-vector-tile-layer / ol-source-vector-tile that uses a projection?  I am using some [NaturalEarth](https://www.naturalearthdata.com/)  datasets as the base layer, but with a [Lambert Conformal Conic](https://epsg.io/102004) (LCC) projection.

The projection is registered using `ol-projection-register`, the `view` specifies that projection, and when the base layer is `ol-source-osm` it loads and fine and is registered properly.  So far, all is good.

I would like to serve NaturalEarth data (and other data) via [tileserv](https://github.com/CrunchyData/pg_tileserv).  When I change out the OSM layer for my own NE layer, the tiles seem to load fine, but are in the wrong place.  If I leave out the `:projection` parameter to the `ol-source-vector-tile` it produces "A VectorTile source can only be rendered if it has a projection compatible with the view projection".  Is there a header in the MVT tiles that is not getting set properly?

All of this worked fine in Vue2 with [vuelayers](https://vuelayers.github.io/#/) (so I know it can be done), but both of those are getting old and I'm trying to upgrade my app.

Thank you for your work on vue3-openlayers.

**Comment by wendellwt** [comment]
I needed to add the `extent`.  It works fine now.
```
    <ol-source-vector-tile :url="mvt_url_admin"
                           :format="mvtFormat"
                           :projection="projectionLCC"
                           :extent="extentLCC"   >
```

and
```
const projectionLCC = "ESRI:102004";
const extentLCC = ref([
          -4250000, // Xmin
          -4250000, // Ymin
           4250000, // Xmax
           4250000, // Ymax
         ]);
```
Thanks again for your hard work on this project.
