### ISSUE TITLE
Cannot use Event emits with ol-map

### ISSUE THREAD

**Issue by ltt2801** [MelihAltintas/vue3-openlayers#259]
According to the docs:
You have access to all Events from the underlying source. Check out [the official OpenLayers docs](https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html) to see the available events tht will be fired.
```
<ol-map @error="handleEvent">
  <!-- ... -->
</ol-map>

```
However, when I tried to use rendercomplete event from openlayers docs 
```
<ol-map @error="handleEvent" @rendercomplete="handleRender">
  <!-- ... -->
</ol-map>
```

function handleRender does not have any response. I know we can use method mapRef.value?.on('rendercomplete, () => {}) but I want to use the emitting event handler.

**Comment by d-koppenhagen** [comment]
Are you using the version `3.0.0-0` or above? The docs already refer to the latest version. I think I will prepare for releasing a final version.

**Comment by d-koppenhagen** [comment]
Please check out version [3.0.0](https://github.com/MelihAltintas/vue3-openlayers/releases/tag/v3.0.0) and take care of potential breaking changes. You should now be able to access the `rendercomplete` event.
Please re-open if not.
