### ISSUE TITLE
vector tile appearance

### ISSUE THREAD

**Issue by wendellwt** [MelihAltintas/vue3-openlayers#261]
Is there a way to improve the appearance of `ol-vector-tile-source` loading?

I have an `ol-vector-tile-layer` that works fine (thank you, btw).  However, the tile source represents moving tracks, and I set the :url property often, and the display goes blank during the url fetch.  Is there a way to improve this appearance?

Would some sort of double-buffering scheme work?  That is, I create two `ol-source-vector-tiles` within div A and div B, and switch between the two based on tile load events as shown in the OL example [here](https://openlayers.org/en/latest/examples/tile-load-events.html)?

That is, something like this:
```
<ol-source-vector-tile v-if="showing_a"
                       :ref="tiles_a"
                       :url="url_a"  ... >

<ol-source-vector-tile v-if="showing_b"
                       :ref="tiles_b"
                       :url="url_b"  ... >
```
and to flip between the two:
```
tiles_a.on( 'tileloadend', function () {
  showing_a = true;
  showing_b = false;
});
tiles_b.on( 'tileloadend', function () {
  showing_a = false;
  showing_b = true;
});
```
and to fetch:
```
if (showing_a) url_b = 'http://whatever?time=1';
if (showing_b) url_a = 'http://whatever?time=2';
```
Is the `'ref'` property of the `ol-source-vector-tile` the correct item to use for the `on('tileloadend')` function?

**Comment by d-koppenhagen** [comment]
Hey, have you tried to define and pass a custom `tileLoadFunction`?
This should give you more flexibility when calling a URL and processing tiles:

https://openlayers.org/en/latest/apidoc/module-ol_source_VectorTile-VectorTile.html

**Comment by wendellwt** [comment]
Thank you, I'll take a look at it.

Do you know if `vue3-openlayers` (or `OpenLayers` itself) does _not_ to anything to the tiles that are currently displayed when `tileLoader` (or the `format.readFeatures()` within tileLoader) are called?  And that the tiles currently displayed are only replaced when `tile.setFeatures(features)` happens?  If so, then that would work, and is much cleaner.

**Comment by d-koppenhagen** [comment]
Sorry I didn't get it. Can you please describe it a bit more?

**Comment by d-koppenhagen** [comment]
I will close this issue as there was no further reponse. Please feel fre to re-open with a detailled description and steps for reporduction.
