### ISSUE TITLE
Missing width in ol-map won't load the map

### ISSUE THREAD

**Issue by ltt2801** [MelihAltintas/vue3-openlayers#264]
In new version 3.0.0, your example is not define a width value, so the map won't load

**Comment by ltt2801** [comment]
I cannot use :controls="defaultControls" in ol-map too

`   
<ol-map
    ref="mapRef"
    style="width:500px; height:500px"
    :controls="defaultControls()"
  />

import { defaults as defaultControls } from 'ol/control'
`

**Comment by d-koppenhagen** [comment]
The map needs a width to get rendered. This is by intention.
