### ISSUE TITLE
Wrong overlay position with EPSG:3857 projection

### ISSUE THREAD

**Issue by OviOvocny** [MelihAltintas/vue3-openlayers#266]
**Describe the bug**
When using the Spherical Mercator projection with `ol-map`, any position set on `ol-overlay` results in the overlay being in the same place (the center of the map), while with the Geodetic system (EPSG:4326) it works normally. [See the two maps here](https://stackblitz.com/edit/vue3-openlayers-template-ppypbw?file=src%2Fcomponents%2FTheMap.vue).

**Affected version(s)**

```
ol-contextmenu@5.3.0
ol-ext@4.0.11
ol@8.1.0
vue@3.3.7
vue3-openlayers@3.0.0
```

**To Reproduce**

1. Create a map with EPSG:3857 projection
2. Add an overlay with a position

**Expected behavior**
No difference between the two projection modes.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Arc (Chromium 118.0.5993.117), Safari 17

**Comment by d-koppenhagen** [comment]
Sorry but I don't get the point. Sure: if you use another projection, the coordinates for this projection must match. So you cannot only change the projection and pass the same coordinates (wich are only related to one of your projections) un-transformed.

**Comment by OviOvocny** [comment]
Yep. That's me, a dumdum, after hours spent playing with the map and staring into the OL docs without any previous maps experience. I can't believe I missed the transformations in the examples. Well, sorry about that.
