### ISSUE TITLE
Reduce size of bundle

### ISSUE THREAD

**Issue by PoloLacoste** [MelihAltintas/vue3-openlayers#268]
**Is your feature request related to a problem? Please describe.**
The size of the package is huge, due to a double export of some packages.
See [here](https://bundlephobia.com/package/vue3-openlayers@3.0.0).

**Describe the solution you'd like**
In the `package.json`, all the `peerDependencies` are present in the `dependencies` which result in a huge bundle size.
When this package is built, it will include the bundle of `ol`, `ol-ext`, etc... 

**Additional context**
I'm trying to build an app in Nuxt with this package for the map.

**Comment by d-koppenhagen** [comment]
Hey, actually it shouldn't include this in the bundles since the rollup option `external` in the vite config is set to face this issue. Removing this makes the bundle size increasing.
