### ISSUE TITLE
All features are positioned over [0,0] if I use the Mercator projection

### ISSUE THREAD

**Issue by ldellisola** [MelihAltintas/vue3-openlayers#272]
**Describe the bug**
Whenever I try to add features to a map that uses the Mercator projection (ESPG:3857) all the features are set in the coordinates [0,0] instead of their respective location.

Here's a simple example to reproduce the bug:
```vue
<template>
  <ol-map
    :loadTilesWhileAnimating="true"
    :loadTilesWhileInteracting="true"
    style="height: 400px"
  >
    <ol-view
      ref="view"
      :center="center"
      :rotation="rotation"
      :zoom="zoom"
      :projection="projection"
    />

    <ol-tile-layer>
      <ol-source-osm />
    </ol-tile-layer>
    <ol-vector-layer>
      <ol-source-vector>
        <ol-feature>
          <ol-geom-point :coordinates="[10.757933, 59.911491]" />
        </ol-feature>
      </ol-source-vector>
      <ol-style>
        <ol-style-stroke color="black" :width="2"></ol-style-stroke>
        <ol-style-fill color="rgba(255,255,255,0.1)"></ol-style-fill>

        <ol-style-circle :radius="10">
          <ol-style-fill color="green"></ol-style-fill>
          <ol-style-stroke color="#fff" :width="1"></ol-style-stroke>
        </ol-style-circle>
        <ol-style-text>
          <ol-style-fill color="#fff"></ol-style-fill>
        </ol-style-text>
      </ol-style>
    </ol-vector-layer>
  </ol-map>
</template>

<script>
import { ref, inject } from 'vue';

export default {
  setup() {
    const center = ref([10, 60]);

    // CHANGE THESE LINES
    // const projection = ref('EPSG:3857');
    const projection = ref('EPSG:4326');
    const zoom = ref(4);
    const rotation = ref(0);

    const format = inject('ol-format');
    const geoJson = new format.GeoJSON();

    return {
      center,
      projection,
      zoom,
      rotation,
      geoJson,
    };
  },
};
</script>

```

If you change the projection to the default one on the examples (ESPG:4326), it works fine.

**Affected version(s)**
```
> npm list --depth=0 vue vue3-openlayers ol ol-ext ol-contextmenu
vue3-openlayers-starter@0.0.0 /home/projects/vue3-openlayers-template
+-- vue@3.2.47
`-- vue3-openlayers@0.1.74
```

**To Reproduce**

1. Go to the StackBlitz playground and paste the Vue component that I defined on the top of this bug report
2. Initially it will use the ESPG:4326 projection, verify that there's a green dot over Oslo, Norway.
3. Comment the line `const projection = ref('EPSG:4326');` and uncomment the line `// const projection = ref('EPSG:3857');`
4. Now the green dot will appear somewhere over the Atlantic, on the [0,0] coordinates.

**Expected behavior**
The green dot should be over Oslo, Norway no matter what projection I'm using.

**Screenshots**
Invalid feature position using the Mercator projection:
![image](https://github.com/MelihAltintas/vue3-openlayers/assets/26941679/e9efd87e-a4b0-42b9-9ecc-d63dc8da11c6)

Correct feature position using the ESPG:3857 projection:
![image](https://github.com/MelihAltintas/vue3-openlayers/assets/26941679/0a8be434-78f2-4f69-a579-339a82fa7380)

**Desktop (please complete the following information):**

- OS: MacOS and Windows
- Browser Firefox, Safari, Edge

**Comment by adamkw** [comment]
A geographical location will have different coordinates in different projections. The coordinates you've used in your example are valid for the `EPSG:4326` projection, representing Oslo. However, these coordinates are not valid in the `EPSG:3857` projection. If you wish to use the `EPSG:3857` projection, you'll need to transform the coordinates. For example, Oslo's coordinates in `EPSG:3857` would be `[1197567.6235481538, 8380058.64380335]`.

For more insight, there's a [nice writeup in the OpenLayers FAQ](https://openlayers.org/doc/faq.html#why-is-my-map-centered-on-the-gulf-of-guinea-or-africa-the-ocean-null-island-). Additionally, OpenLayers offers a utility function to transform coordinates between projections, which is also mentioned in an example in the FAQ.

**Comment by ldellisola** [comment]
I was not aware of that. Thanks!
