### ISSUE TITLE
Can't use vue3-openlayers with yarn

### ISSUE THREAD

**Issue by laurentleb-comnum** [MelihAltintas/vue3-openlayers#273]
**Describe the bug**
I have tried to install dependencies then vue3-openlayers using yarn add. 
I get a message "error An unexpected error occurred: "expected hoisted manifest for \"vue3-openlayers#vue#@vue/server-renderer#@vue/compiler-ssr\"".

With npm, looks ok. Obviously, when trying to build, I get the same message.

When using tags in my vues, page is loaded but map doesn't display.

Any idea ? I would like to continue using yarn.

**Affected version(s)**

├── ol-contextmenu@5.3.0
├── ol-ext@4.0.11
├── ol@8.1.0
├── vue@3.3.2
└── vue3-openlayers@3.1.0

Thanks in advance for your help

**Comment by d-koppenhagen** [comment]
Hey, have you tried to remove your `yarn.lock` file and run `yarn install` afterwards?

**Comment by laurentleb-comnum** [comment]
Hey, yes I did, no change unfortunately

**Comment by laurentleb-comnum** [comment]
Hello,
I did not succeed in using vue3 opelayers but still want hardly !
I have tried to add explicitely the vue server-rendere and compile-ssr in my package.json, it makes no difference
Do you have an idea ? I saw that these package are in your package lock file but not in your package.json, could it come from there ? 
Thanks in advance
