### ISSUE TITLE
Can't use icon png or svg into ol-webgl-points-layer style

### ISSUE THREAD

**Issue by ChrisD92** [MelihAltintas/vue3-openlayers#274]
**Describe the bug**
I tried to use icon-src like this exemple : https://openlayers.org/en/latest/examples/webgl-points-layer.html,
but i have systematically this error : 

Uncaught Error: Fragment shader compilation failed: ERROR: 0:1: 'null' : syntax error
    getProgram Helper.js:895
    afterHelperCreated PointsLayer.js:341
    prepareFrame Layer.js:187
    render Layer.js:370
    renderFrame Composite.js:128
    renderFrame_ Map.js:1584
    animationDelay_ Map.js:1423
    render Map.js:1456
    handleSizeChanged_ Map.js:1231
    dispatchEvent Target.js:114
    notify Object.js:184
    set Object.js:223
    setSize Map.js:1662
    updateSize Map.js:1740
    handleTargetChanged_ Map.js:1337
    dispatchEvent Target.js:114
    notify Object.js:184
    set Object.js:223
    setTarget Map.js:1673
    setup vue3-openlayers.es.js:336
    node_modules chunk-H65YMOS6.js:8597
    callWithErrorHandling runtime-core.esm-bundler.js:158
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    __weh runtime-core.esm-bundler.js:2721
    flushPostFlushCbs runtime-core.esm-bundler.js:330
    flushJobs runtime-core.esm-bundler.js:368
    promise callback*queueFlush runtime-core.esm-bundler.js:275
    queuePostFlushCb runtime-core.esm-bundler.js:295
    resolve runtime-core.esm-bundler.js:1461
    registerDep runtime-core.esm-bundler.js:1567
    promise callback*registerDep runtime-core.esm-bundler.js:1531
    mountComponent runtime-core.esm-bundler.js:5652
    processComponent runtime-core.esm-bundler.js:5612
    patch runtime-core.esm-bundler.js:5087
    componentUpdateFn runtime-core.esm-bundler.js:5755
    run reactivity.esm-bundler.js:178
    update runtime-core.esm-bundler.js:5861
    setupRenderEffect runtime-core.esm-bundler.js:5869
    registerDep runtime-core.esm-bundler.js:1545
    promise callback*registerDep runtime-core.esm-bundler.js:1531
    mountComponent runtime-core.esm-bundler.js:5652
    processComponent runtime-core.esm-bundler.js:5612
    patch runtime-core.esm-bundler.js:5087
    mountSuspense runtime-core.esm-bundler.js:1176
    process runtime-core.esm-bundler.js:1122
    patch runtime-core.esm-bundler.js:5112
    mountChildren runtime-core.esm-bundler.js:5331
    mountElement runtime-core.esm-bundler.js:5238
    processElement runtime-core.esm-bundler.js:5203
    patch runtime-core.esm-bundler.js:5075
    mountChildren runtime-core.esm-bundler.js:5331
    mountElement runtime-core.esm-bundler.js:5238
    processElement runtime-core.esm-bundler.js:5203
    patch runtime-core.esm-bundler.js:5075
    componentUpdateFn runtime-core.esm-bundler.js:5755
    run reactivity.esm-bundler.js:178
    update runtime-core.esm-bundler.js:5861
    setupRenderEffect runtime-core.esm-bundler.js:5869
    mountComponent runtime-core.esm-bundler.js:5659
    processComponent runtime-core.esm-bundler.js:5612
    patch runtime-core.esm-bundler.js:5087
    mountChildren runtime-core.esm-bundler.js:5331
    mountElement runtime-core.esm-bundler.js:5238
    processElement runtime-core.esm-bundler.js:5203
    patch runtime-core.esm-bundler.js:5075
    componentUpdateFn runtime-core.esm-bundler.js:5755
    run reactivity.esm-bundler.js:178
    update runtime-core.esm-bundler.js:5861
    setupRenderEffect runtime-core.esm-bundler.js:5869
Helper.js:895:12
WebGL warning: linkProgram: Must have a compiled vertex shader attached:
SHADER_INFO_LOG:
ERROR: 0:1: 'null' : syntax error

**Affected version(s)**

latest

```
<VERSION_OUTPUT>
```

**To Reproduce**

Use style variable declared like this : 

const pointsStyle = {
'icon-src': './icon.png',
'icon-width': 18,
'icon-height': 28,
'icon-color': 'lightyellow',
'icon-rotate-with-view': false,
'icon-displacement': [0, 9],
}

**Expected behavior**

Having point with icon image like png or jpeg or svg

**Screenshots**

no

**Desktop (please complete the following information):**

- OS: ubuntu 20.04
- Browser firefox

**Smartphone (please complete the following information):**

no

**Additional context**

I think that the styles is not parsed correctly. Any idea or functional example ?

**Comment by d-koppenhagen** [comment]
Hey, you have to import the icon and pass it as string. See: https://github.com/MelihAltintas/vue3-openlayers/commit/feb216bc330d0bd2187f73ced1bea801c3992c03 , I added an example to the docs.
