### ISSUE TITLE
Have plan to dist WebComponents version.

### ISSUE THREAD

**Issue by shiftonetothree** [MelihAltintas/vue3-openlayers#275]
Could it use on react.

Maybe we can dist a WebComponents version just by change less code.

Vue3 have well support for develop WebComponents

**Comment by d-koppenhagen** [comment]
I am not sure how to do this efficently. Have you done it already? Do you want to contribute? I am not really sure if WebComponents will work good as some propetier are passed as objects or even classes throught the components. Also they rely on Vue's provide/inject mechanism which won't work in WebComponents. All in all I am quite sceptic if it will work as designed with WebComponents. But: Feel free so try it out and send a PR for discussion.

**Comment by shiftonetothree** [comment]
Thanks for invite, I hope I can, but I'm doing a full time job now, can't contribute to opensource now.
