### ISSUE TITLE
Uncaught TypeError: tileRepresentationLookup.representationsByZ[z3] is not iterable

### ISSUE THREAD

**Issue by Miltonbhowmick** [MelihAltintas/vue3-openlayers#276]
**Describe the bug**
I was using the vue3 openlayers properly from couple of months. But i am facing an error suddenly today when i moving the map after drawing a polygon.

**Affected version(s)**

`vue3-openlayers": "^1.2.0`

**Expected behavior**
It did not show any error after drawing polygon. It was so nice to use.

**Screenshots**
![vue3 openlayer issue](https://github.com/MelihAltintas/vue3-openlayers/assets/16919385/a6e367d8-6944-4ab2-b6e2-fe99df6271dd)

**Desktop (please complete the following information):**

- Windows 11
- Chrome Browser

**Comment by d-koppenhagen** [comment]
Hey, did the problem occur after a version update? Or did something else changed like the data / layer source? Can you provide a minimum example for reproduction?

**Comment by Miltonbhowmick** [comment]
It might be after a version update but i am not sure. I just start work after couple of weeks in my Nuxt.js project and i was just testing without any change of code. And i am seeing this error.

> Hey, did the problem occur after a version update? Or did something else changed like the data / layer source? Can you provide a minimum example for reproduction?

**Comment by d-koppenhagen** [comment]
It could be causes by an update of openlayers itself. Did you updated to OpenLayers 7? In this case you have to update vue3-openlayers too and use the latest version. Be aware of the Webgl related Breaking Changes. Since there was not minor or fix release for v1 of vue3-openlayers, some other dependency update seems to cause this side effect.
