### ISSUE TITLE
reactivity, opacity and so on

### ISSUE THREAD

**Issue by bmanojlovic** [MelihAltintas/vue3-openlayers#277]
**Describe the bug**
reactivity in vue works as is but values do not change for opacity or visibility (just opacity in version bellow) on openlayers level
at all, yeah i assume it is something totally trivial but can't figure out what
https://stackblitz.com/edit/vitejs-vite-34ktn3?file=src%2Fcomponents%2FTheMap.vue
**Affected version(s)**

Please run `npm list --depth=0 vue vue3-openlayers ol ol-ext ol-contextmenu` and paste the output below:

```
<VERSION_OUTPUT>
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 14]
- OS: [e.g. iOS 16.15.1]

**Additional context**

**Comment by d-koppenhagen** [comment]
To make values reactive, the should be wraped into a `ref`:

```diff
-const center = fromLonLat([21.0059, 44.0165]);
-const zoom = 7;
-const projection = 'EPSG:3857';
-const osmVisible = true;
+const center = ref(fromLonLat([21.0059, 44.0165]));
+const zoom = ref(7);
+const projection = ref('EPSG:3857');
+const osmVisible = ref(true);
```

**Comment by bmanojlovic** [comment]
are you joking???
const layerOpacity = ref(0.99);
 and that is a problematic value osmVisible is not relevant at all

**Comment by bmanojlovic** [comment]
let me slowly explain.... 
there is slider that you can slide around and its value is REACTIVE and it does not work at all
and to prove MY point of reactive thing i have added     <div>{{ layerOpacity }}</div> so you can understand 
https://stackblitz.com/edit/vitejs-vite-hnwumw?file=src%2Fcomponents%2FTheMap.vue

**Comment by d-koppenhagen** [comment]
Okay, now I got the point. Sorry. I repoened it. I think it's a bug in the tileLayer implementation. I Will take over the example in the demo app and reproduce and fix it. But it will take a bit of time. Feel free to investigate by yourself and send me a PR if you are faster :)

**Comment by bmanojlovic** [comment]
i did investigate and did not find really anything problematic to be honest, not an expert in programming - but will try to investigate more
