### ISSUE TITLE
OlSourceTianDiTu should be OlSourceTianditu is better

### ISSUE THREAD

**Issue by shiftonetothree** [MelihAltintas/vue3-openlayers#281]
**Describe the bug**
OlSourceTianDiTu is not for vue template <ol-source-tianditu/>, it's work for <ol-source-tian-di-tu/>.
OlSourceTianditu will be right for <ol-source-tianditu/>;

**Affected version(s)**
```
├── ol-contextmenu@5.3.0
├── ol-ext@4.0.12
├── ol@8.2.0
├── vue@3.3.9
└── vue3-openlayers@3.1.0
```

**To Reproduce**
<template>
      <ol-source-tianditu />
</template>
<script setup lang="ts">
import {Sources} from "vue3-openlayers"

const { 
  OlSourceTianDiTu,
} = Sources
</script>

**Expected behavior**
typescript works well

**Screenshots**
![企业微信截图_5bc2f154-d395-4b63-abed-8ebe6ce0ded6](https://github.com/MelihAltintas/vue3-openlayers/assets/10464106/3e3029a8-fbb3-4534-bd65-46ae90820be6)

![企业微信截图_8141f197-7d20-473c-8195-432a07cefc41](https://github.com/MelihAltintas/vue3-openlayers/assets/10464106/2612e163-f13e-40e5-9377-4025cfe4c5cb)

- OS: macOS
- Browser chrome

**Comment by d-koppenhagen** [comment]
okay, I got what you mean I think. So correct would be `ol-source-tian-di-tu` and not `ol-source-tianditu`? Currently it's explicitely named as `ol-source-tianditu`. I think `Tianditu` is the correct spelling isn't it (at least Wikipedia says it: https://en.wikipedia.org/wiki/Tianditu). So the Component should be renamed.

**Comment by d-koppenhagen** [comment]
That's what ChatGPT says:

> The correct term in English would typically be "Tianditu." While "Tian Di Tu" and "Tian-Di-Tu" are variations of the same term, the Pinyin romanization system used for Mandarin Chinese usually represents it as "Tianditu" without spaces or hyphens. Pinyin is the official romanization system for Standard Mandarin in mainland China.

**Comment by shiftonetothree** [comment]
> That's what ChatGPT says:
> 
> > The correct term in English would typically be "Tianditu." While "Tian Di Tu" and "Tian-Di-Tu" are variations of the same term, the Pinyin romanization system used for Mandarin Chinese usually represents it as "Tianditu" without spaces or hyphens. Pinyin is the official romanization system for Standard Mandarin in mainland China.

Thanks, Tianditu good for me in typescript.
