### ISSUE TITLE
Testing via nuxt-vitest fails: Cannot find module

### ISSUE THREAD

**Issue by thielpeter** [MelihAltintas/vue3-openlayers#286]
**Describe the bug**
Testing via nuxt-vitest fails:
`Cannot find module '/node_modules/vue3-openlayers/node_modules/ol/Feature' imported from /node_modules/vue3-openlayers/dist/vue3-openlayers.es.js Did you mean to import ol/Feature.js?`

**Affected version(s)**

```
 ol-ext@4.0.13
├── ol@7.3.0
└── vue3-openlayers@3.2.0
```

**To Reproduce**

Setup nuxt-vitest and run npm test (https://nuxt.com/modules/vitest)

**Expected behavior**
Modules should be imported without file extension

**Note**
Removing "type": "module" from package.json solves the problem

**Comment by d-koppenhagen** [comment]
I think removing type module from this package is not the best solution. It should be possible to fix with some tsconfig adjustment shouldn't it?

**Comment by jsolly** [comment]
I do not have any issues with Vitest + Nuxt + vue3-openlayers. If you share more information like your test file, tsconfig, and package.json, that might help.

**Comment by stinlemp** [comment]
I've set up a test project and get the same error without nuxt-vitest now. We work in a special environment so we cant install nuxt the way its documented. Here is how the setup looks.

nuxt.config.ts
```
export default defineNuxtConfig({
  ssr: false, // if true same error on npm run dev
  modules: ['nuxt-vitest']
})
```

package.json
```
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "test": "vitest"
  },
  "devDependencies": {
    "nuxt": "^3.3.1",
    "vue-router": "latest"
  },
  "dependencies": {
    "happy-dom": "^12.10.3",
    "nuxt-vitest": "^0.11.5",
    "vue3-openlayers": "^4.0.1"
  }
}
```
tsconfig.json 
```
{
  "extends": "./.nuxt/tsconfig.json"
}
```
plugins/vue3-openlayers.js
```
// plugins/vue3-openlayers.client.js
import { defineNuxtPlugin } from '#app'
import OpenLayers from 'vue3-openlayers'

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.vueApp.use(OpenLayers)
})
```

app.vue
```
<template>
    <div>
    <h1>Hello World!</h1>

    <ol-map
        :loadTilesWhileAnimating="true"
        :loadTilesWhileInteracting="true"
        style="height: 400px"
    >
        <ol-view
            ref="view"
            :center="center"
            :rotation="rotation"
            :zoom="zoom"
            :projection="projection"
        />

        <ol-tile-layer>
        <ol-source-osm />
        </ol-tile-layer>
    </ol-map>
    </div>
</template>

<script setup>
    import { ref } from "vue";

    const center = ref([40, 40]);
    const projection = ref("EPSG:4326");
    const zoom = ref(8);
    const rotation = ref(0);
</script>
```

**Comment by stinlemp** [comment]
Issue could be solved by adding to nuxt.config:

```
...
@test {
 build: {
  transpile: [vue3-openlayers]
 }
}
```
