### ISSUE TITLE
Impossible to set height and width on icon

### ISSUE THREAD

**Issue by mwargan** [MelihAltintas/vue3-openlayers#288]
https://github.com/MelihAltintas/vue3-openlayers/blob/27ebc4b24a669d74eb1eabf799659560a6cc5b48/src/components/styles/OlStyleIcon.vue#L20

We can use `height` or `width` on our icons according to OSLayers, but for this, the `scale` needs to be `undefined`, otherwise it fails the assert. See https://github.com/openlayers/openlayers/blob/9fc75eb74eb6097ab9e7713b6e19f7fe0f3ac261/src/ol/style/Icon.js#L179

However, we cannot set undefined with `:scale="undefined"` because Vue will then just use the default, which is 1 in this case.

## Proposal
Set undefined by default in the props (breaking change), or otherwise rework logic to support undefined as a passed value.

**Comment by d-koppenhagen** [comment]
Fix is released on with v4.0.0
