### ISSUE TITLE
option to HIDE vector layers in ol-layerswitcherimage-control Menu

### ISSUE THREAD

**Issue by signmeuptwice** [MelihAltintas/vue3-openlayers#29]
would be nice to be able to hide Vector layers like drawings from ol-layerswitcherimage-control menu (vectors still displayed of course)

at the moment the menu always shows this extra layer even if no drawings are present

something like
`<ol-layerswitcherimage-control :vectorLayers="false" />`

**Describe alternatives you've considered**
removing manually with ol functions but that seems terribly wrong to instantiate something just to remove it

**Comment by MelihAltintas** [comment]
Ol-layerswitcherimage-control already has a prop

displayInLayerSwitcher | function | function that takes a layer and return a boolean if the layer is displayed in the switcher, default test the displayInLayerSwitcher layer attribute
-- | -- | --

For doc: https://viglino.github.io/ol-ext/doc/doc-pages/ol.control.LayerSwitcher.html

**Comment by signmeuptwice** [comment]
great, thanks for the tip; i'll have a look

Would still be nice to have more abstraction
