### ISSUE TITLE
Memory Leak on Docs

### ISSUE THREAD

**Issue by mwargan** [MelihAltintas/vue3-openlayers#290]
**Describe the bug**

If you go to https://vue3openlayers.netlify.app/demo.html and profile the page, you'll see a massive spike up to 286mb in JS heap 
<img width="1361" alt="image" src="https://github.com/MelihAltintas/vue3-openlayers/assets/13789481/6d53593f-8f6d-41cf-bcd5-050f5e25dba9">

**Affected version(s)**

I have a feeling that this wasn't the case before version 4, but this is purely speculative. Its just that I don't remember the docs crashing/getting-slow like this before

**To Reproduce**

1. Go to the demo page.
2. Scroll up and down, notice slowness and it getting stuck

**Comment by mwargan** [comment]
<img width="1360" alt="image" src="https://github.com/MelihAltintas/vue3-openlayers/assets/13789481/e317fb14-90a2-47e4-9d37-dacbd2c868d3">

I tried with 3.2.1 and 4.0.0 on my project and didn't see any leaks per se, I think it may be related to the docs rather than the package itself but don't take my word for it

**Comment by d-koppenhagen** [comment]
Thank you. I checked the docs and it seems like, the webgl-points-layer causes the app beaking. I will porobably remove this layer from the combined demo.

**Comment by mwargan** [comment]
> Thank you. I checked the docs and it seems like, the webgl-points-layer causes the app beaking. I will porobably remove this layer from the combined demo.

Fantastic ok! 

Does this mean there's another potential bug hiding in the webgl-points-layer we should be aware of?
