### ISSUE TITLE
Component as icon

### ISSUE THREAD

**Issue by KaevN** [MelihAltintas/vue3-openlayers#295]
I'm trying to convert a project from leaflet to openlayers. In my project, I need to display custom icons on the map, but the problem is that for this I used a component that changes visually depending on the props. ol-style-icon only accepts the scr of the icon itself, this does not suit me, is there an option to use a Vue component as an icon?
<img width="375" alt="image" src="https://github.com/MelihAltintas/vue3-openlayers/assets/63998986/4a12c81c-7425-4343-9736-496faee9c03a">

**Comment by d-koppenhagen** [comment]
We had a pretty similar problem in the past. As far as I know there is currently no such direct feature.
Our solution was to generate an SVG and return an SVG inline data URL. This URL we passed as the `src`. It worked since the component generated the URL based on the input params.

**Comment by KaevN** [comment]
> We had a pretty similar problem in the past. As far as I know there is currently no such direct feature. Our solution was to generate an SVG and return an SVG inline data URL. This URL we passed as the `src`. It worked since the component generated the URL based on the input params.

interesting solution, can you be more specific, are you generating svg from a Vue component? if yes, what tool?

**Comment by d-koppenhagen** [comment]
I am simply building the SVG string and put it into a data URL.
With this tool, you can try it out: https://yoksel.github.io/url-encoder/
