### ISSUE TITLE
Nuxt3 Configuration

### ISSUE THREAD

**Issue by melfag** [MelihAltintas/vue3-openlayers#296]
**Is there a way to add this library to an existing Nuxt 3 project?**
I followed the official Nuxt docs but was unable to get this to work. Is there something in the docs that I particularly missed?

**Comment by d-koppenhagen** [comment]
Hey @melfag as commonly people asking nuxt questions: would you mind to share your solution and how you got it working? Or even better: contribute a section to the docs?
