### ISSUE TITLE
ol-layerswitcherimage-control Implement Groups to separate base layers from vector layer + user options prop

### ISSUE THREAD

**Issue by signmeuptwice** [MelihAltintas/vue3-openlayers#30]
`ol-layerswitcherimage-control` is frustrating
base layers should be displayed as `radio` to only have one selected at a time by default
From doc this is normally done by putting type='base' on the layer

We also need a user object to define custom groups

**Describe the solution you'd like**
props on the component

**Comment by MelihAltintas** [comment]
In 0.1.45 version The baseLayer layer's property manage exclusive visibility on layers (only one base layer is shown at a time).
```
    <ol-tile-layer ref="osmLayer" title="OSM" :baseLayer="true">
        <ol-source-osm />
    </ol-tile-layer>


```

**Comment by signmeuptwice** [comment]
still don't have radio style toggle after adding the prop :/
behavior is the exact same

**Comment by MelihAltintas** [comment]
only select one layer at a time
example : https://codesandbox.io/s/radiio-ghx48?file=/src/components/Comp.vue

**Comment by signmeuptwice** [comment]
yes it works in codebox, so must be a conflict on my end because I have same code and the latest version...
I have the same code so weird
will keep digging I might have to do it manually somehow

**Comment by signmeuptwice** [comment]
<ol-tile-layer ref="osmLayer" title="Normal" :visible="true" :baseLayer="true">
        <ol-source-osm />
      </ol-tile-layer>

      
      <ol-tile-layer ref="googleLayer" title="Satellite" :visible="false" :baseLayer="true">
        <ol-source-xyz
            attributions='<a href="https://www.google.at/permissions/geoguidelines/attr-guide.html">Map data ©2015 Google</a>'
            url="https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}"
            title="Satellite"
        >
        </ol-source-xyz>
      </ol-tile-layer>


      
      
      <ol-tile-layer ref="cyclingLayer" title="Cycling" :visible="false" :baseLayer="true">
        <ol-source-xyz
            attributions='<a href="https://www.google.at/permissions/geoguidelines/attr-guide.html">Map data ©2015 Google</a>'
            url="https://tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=957117711bdb40a9b261303a25d072d9"
            title="Satellite"
        >
        </ol-source-xyz>
      </ol-tile-layer>

      
      <ol-tile-layer  ref="outdoorLayer" title="Outdoors" :visible="false" :baseLayer="true">
        <ol-source-xyz
            attributions='<a href="https://www.google.at/permissions/geoguidelines/attr-guide.html">Map data ©2015 Google</a>'
            url="https://tile.thunderforest.com/outdoors/{z}/{x}/{y}.png?apikey=957117711bdb40a9b261303a25d072d9"
            title="Satellite"
        >
        </ol-source-xyz>
      </ol-tile-layer>

      
      <ol-tile-layer  ref="landscapeLayer" title="Landscape" :visible="false" :baseLayer="true">
        <ol-source-xyz
            attributions='<a href="https://www.google.at/permissions/geoguidelines/attr-guide.html">Map data ©2015 Google</a>'
            url="https://tile.thunderforest.com/landscape/{z}/{x}/{y}.png?apikey=957117711bdb40a9b261303a25d072d9"
            title="Satellite"
        >
        </ol-source-xyz>
      </ol-tile-layer>

**Comment by MelihAltintas** [comment]
No problem : https://codesandbox.io/s/radiio-forked-55rur?file=/src/components/Comp.vue

**Comment by signmeuptwice** [comment]
yep... I don't get it, my code works in sandbox but not in project... humm

**Comment by MelihAltintas** [comment]
Make sure vue3-openlayers version is 0.1.45 in package.json :)

**Comment by signmeuptwice** [comment]
that did it; I had "*" before

thank you :)
