### ISSUE TITLE
support for WebGL Lines and Polygons?

### ISSUE THREAD

**Issue by wendellwt** [MelihAltintas/vue3-openlayers#300]
How difficult would it be to add support for WebGL Lines and Polygons?

There is a demo on the ol examples page ([WebGL Vector Layer](https://openlayers.org/en/latest/examples/webgl-vector-layer.html)).  It is tagged as 'not part of the stable API', but it seems to work fine.

Would it be a matter of copying [OlWebglPointsLayer ](https://github.com/MelihAltintas/vue3-openlayers/blob/main/src/components/layers/OlWebglPointsLayer.vue) to a new OLWebglVectorLayer and making it do the things in the ol example page?  I suppose there should be a Vector version of the source [OlSourceWebglPoints ](https://github.com/MelihAltintas/vue3-openlayers/blob/main/src/components/sources/OlSourceWebglPoints.vue) , and also corresponding demos for both of those.

If the response is 'contribution welcome' (!), then I could try to do a fork/edit/pullreq, but would need guidance and advice.  I would be starting with:

| WebGL | OL    | vue3-ol    |
| ---   | --- | --- |
| PointsLayer | Y | Y |
| PointsSource | Y| Y |
| PointsDemo | Y | Y |
| VectorLayer | Y |  |
| VectorSource | Y|  |
| VectorDemo | Y |  |

and it would just be a 'simple' matter of filling in the missing parts.

Thank you for all of the work on vue3-openlayers.

**Comment by d-koppenhagen** [comment]
Of course! Feel free to contribute. Copying one of the existing components is a good start.
You can start and send a draft PR if you are unsure and I will make suggestions for changes / can tell you what's missing.
When creating the component, please be sure most of the properties should be passed from OpenLayers to the component as props directly (don't create new fancy names or so).

**Comment by wendellwt** [comment]
Ok, I tried, and I issued a PR, but it is somewhat rough.  I want to use WebGL for Lines, and the OL changes seem to work for both Lines and Polygons, so there are some places in `OlSourceWebglVector.vue` that have 'Line' where they should be 'Line|Polygon' or maybe even 'Any'; I'm not sure how to make it work for both.
