### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by tpzar** [MelihAltintas/vue3-openlayers#302]
Hello,
How to bind a tooltip to a geometry like ol-geom-point, so if cursor passes over a geometry, a text box appears?
Thank you

**Comment by d-koppenhagen** [comment]
Hey @tpzar you can use the ineraction select with hover condition (similar to this: https://vue3openlayers.netlify.app/componentsguide/interactions/select/).
You will receive a `select` event with the points data (such as coordinates). This you can use for showing the overly at the right position.

**Comment by d-koppenhagen** [comment]
See also the complete Demo: https://vue3openlayers.netlify.app/demo.html
