### ISSUE TITLE
Component not found on createApp reload

### ISSUE THREAD

**Issue by signmeuptwice** [MelihAltintas/vue3-openlayers#31]
Reproduction link

[codesandbox.io](https://codesandbox.io/embed/nervous-leavitt-m8x6b?fontsize=14&hidenavigation=1&theme=dark)

Steps to reproduce

       function loadEvent(resumeData = null) {
          createApp(eventMainComponent, {resumeData: resumeData}).use(OpenLayersMap).mount("#Vue-events")
        }

What is expected?

Component uses OpenLayersMap

What is actually happening?

Not sure if this is related to OpenLayers or Vue3-OpenLayers or simply Vue3
problem is OpenLayersMap not found inside the created app on a reload
in the sandbox you see the map disappear on reload
My application is not a full vue application
my menu loads vue instances in the website dynamically

for example I click on Events and this will trigger the following code:

        import OpenLayersMap from 'vue3-openlayers'
        createApp(eventMainComponent,{resumeData:resumeData}).use(OpenLayersMap).mount("#Vue-events")

works like a charm the first time but I switch to another page lets say blog

then if I reload Events that will execute the same code above I get

        [Vue warn]: injection "ol-format" not found. which refers to const format = inject('ol-format');

**Comment by MelihAltintas** [comment]
this is not related to lib.

**Comment by signmeuptwice** [comment]
I agree
I posted on vue@next and they told me to post on your lib lol
