### ISSUE TITLE
Example for ol-source-geo-tiff doesn't work

### ISSUE THREAD

**Issue by christophfriedrich** [MelihAltintas/vue3-openlayers#310]
**Describe the bug**

The example on how to use the GeoTIFF component (`ol-source-geo-tiff`) doesn't work:

> ![image](https://github.com/MelihAltintas/vue3-openlayers/assets/17781682/6a49afc1-0a46-4b0c-ada1-aff52aa7474b)
> 
> _Screenshot of https://vue3openlayers.netlify.app/componentsguide/sources/geotiff/_

This is what it looks like in Firefox 123. I didn't have an instance of Chrome at hand to test it there, but did open Edge (which is Chromium-based) for a very brief moment to test it there and the result was identical.

Looking at the Network tab in the dev panel, one sees that [the COG](https://s2downloads.eox.at/demo/EOxCloudless/2020/rgbnir/s2cloudless2020-16bits_sinlge-file_z0-4.tif) does get loaded in the background, but the map stays white anyway. It's the same in my own application using e.g. [this COG](https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/33/U/UV/2017/8/S2B_33UUV_20170830_0_L2A/TCI.tif). Note that both are files with multiple bands. Using multiple *files* with a *single band each* works, i.e. replacing the `sources` array with e.g. this:

```js
[
  {
    url: 'https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/33/U/UV/2023/7/S2A_33UUV_20230715_0_L2A/B04.tif',
    max: 10000,
  },
  {
    url: 'https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/33/U/UV/2023/7/S2A_33UUV_20230715_0_L2A/B03.tif',
    max: 10000,
  },
  {
    url: 'https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/33/U/UV/2023/7/S2A_33UUV_20230715_0_L2A/B02.tif',
    max: 10000,
  },
]
```

NB: The Stackblitz starter template still uses an 0.x version of vue3-openlayers, not an 3.x+ one where this component is available.

**Affected version(s)**

On my local machine `npm list --depth=0 vue vue3-openlayers ol ol-ext ol-contextmenu` returns:

```
├── ol-contextmenu@5.3.0
├── ol-ext@4.0.12
├── ol@8.2.0
├── vue@3.3.8
└── vue3-openlayers@3.1.0
```

(I just noticed that meanwhile there's version 6.x (I love the active development here!) -- I'm sorry if it's already fixed in a newer release, I'll check that with my local code base tomorrow, but as the official example page is affected too I'm gonna send this issue now anyway.)

**To Reproduce**

1. Go to https://vue3openlayers.netlify.app/componentsguide/sources/geotiff/
2. See error

**Expected behavior**
A non-white map that correctly displays the COG.

**Screenshots**
See above

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Firefox 123

**Comment by christophfriedrich** [comment]
Okay, I just upgraded my local codebase to v6.0 (which as a side effect produced PR #311) and can confirm that the behaviour is still the same: No multi-band COG to be seen.

**Comment by bmanojlovic** [comment]
i have tried it and it does work for me when there is opacity (but CORS issue i get can't resolve), but i do agree this is not correct "fix" at all
```
diff --git a/src/App.vue b/src/App.vue
index 547fa17..ef56ed3 100644
--- a/src/App.vue
+++ b/src/App.vue
@@ -29,7 +29,7 @@
       <ol-source-osm />
     </ol-tile-layer>
 
-    <ol-webgl-tile-layer :style="evi" ref="layer">
+    <ol-webgl-tile-layer :opacity="1" :style="evi" ref="layer">
       <ol-source-geo-tiff ref="source"
         :sources="[
           {
```
![image](https://github.com/MelihAltintas/vue3-openlayers/assets/200226/8c6385ee-c966-4716-a13a-64fb1b301c55)

**Comment by christophfriedrich** [comment]
Thanks for looking into it Boris, but sadly I can't confirm. As I said I already tried adding `:opacity="1"`. After your comment I tried again, but no, it doesn't fix it. Guessing from your screenshot, I think you took the wrong thing as "success" -- this is what it should look like:

![image](https://github.com/MelihAltintas/vue3-openlayers/assets/17781682/c50d0d9a-45cb-40f5-94a8-cc72ae931f58)

The CORS error can be ignored, it's from an unrelated part (a request to an API that we moved since I wrote that code).

**Comment by d-koppenhagen** [comment]
Fixed in latest versions:
- 4.1.2
- 5.0.2
- 6.1.2

**Comment by christophfriedrich** [comment]
Thanks for the fix Danny! Very much appreciate it! Works beautifully now.

I spotted that you changed `ref` back to `computed` in OlWebglTileLayer only, while in the bugged commit the same change was [also applied in OlTileLayer](https://github.com/MelihAltintas/vue3-openlayers/commit/c1408beee0674960dbf9b60e68bb6bd315f3ae3f#diff-03e5c7f9ad71b37eefd6f3cac7931f0803063d0c68618019448c61d13b8cb6c3L45), and [in OlImageLayer](https://github.com/MelihAltintas/vue3-openlayers/commit/c1408beee0674960dbf9b60e68bb6bd315f3ae3f#diff-fcbddee1e715940c1d982195c13413c7ab507c289bea0a9ce9e8e83d9f0406b3R28) there is also only a `ref`. Would the same fix need to be applied there too?
