### ISSUE TITLE
vue3-Openlayers: Change Feature color according to properties on the fly from template

### ISSUE THREAD

**Issue by signmeuptwice** [MelihAltintas/vue3-openlayers#32]
I have these features

     <ol-vector-layer title="Features" :visible="vectorMenuDisplay" >
        <ol-source-vector ref="sourceVectorNew" :projection="projection" :features="existingFeatures">
          <ol-interaction-modify v-if="!mapLock && modifyEnabled" :features="selectedFeatures" @modifyend="modifyend"></ol-interaction-modify>
          <ol-interaction-draw v-if="!mapLock && drawEnable" :type="drawType" @drawend="drawend"></ol-interaction-draw>
        </ol-source-vector>
        <ol-style>
          <ol-style-stroke color="red" :width="5"></ol-style-stroke>
          <ol-style-fill color="rgba(255,255,255,0.1)"></ol-style-fill>
          <ol-style-circle :radius="7">
            <ol-style-fill color="green"></ol-style-fill>
            // this color should be from extra data in properties of the feature
          </ol-style-circle>
        </ol-style>
      </ol-vector-layer> 

I would like to change the color="green" dynamically depending on dynamically inserted extra data in properties of the feature

Is it possible ?

**Comment by MelihAltintas** [comment]
Before open the issue please read the doc and examples, in demo page we have example you can easily change the style with  overrideStyleFunction props <ol-style :overrideStyleFunction="overrideStyleFunction">

```
        const overrideStyleFunction = (feature, style) => {

            let properties= feature.get('bla bla bla');  //from extra data in properties of the feature
           if(properties == "....") // change the style
            style.getImage().getFill().setColor("red");
        
        }
```

**Comment by signmeuptwice** [comment]
Thank you, I guess it should work but I always get the first color calculated by function; all my points are the same color

here is my function

    const overrideStyleFunction = (feature, style) => {
      const difficulty = feature.get('difficulty');
      const mode = feature.get('mode')
      let color = getPointColor(mode, difficulty) // right colors here
      style.getImage().getFill().setColor(color);  // wrong colors here after first feature
    }
