### ISSUE TITLE
Cluster : updating regularly coordinates features

### ISSUE THREAD

**Issue by ChrisD92** [MelihAltintas/vue3-openlayers#323]
**Describe the bug**
When I use ol-cluster for displaying the position of multiple vehicule, which are tracked by GPS and fetch with api, the number of features explosed as exponential. I update features with new vehicule income or update mooving vehicule position by changing their coordinates every 3 seconds. But after a few minutes, the navigator freeze, and the console display an error message running out of memory. 
Do you have any idea about this issue ?

**Affected version(s)**

Latest 6.3

```
<VERSION_OUTPUT>
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 14]
- OS: [e.g. iOS 16.15.1]

**Additional context**

**Comment by d-koppenhagen** [comment]
Hey @ChrisD92 thanks for reporting. I am currently on my investigation of some potential leaks here. But to investigate it more easily: can you provide a minimal reproduction scenario (repo, Stackblitz, etc.)?

**Comment by d-koppenhagen** [comment]
Oh an are you using the AnimatedClusterLayer or a vector layer using the ClusterSource?
Can you try out the latest version (I recently made some adjustments which could solve your problem).

**Comment by d-koppenhagen** [comment]
I will closes this for now, as there was not response. Please update to the latest version 8.0.0 and try again.
If the problem still exists, please provide a minimum reproduction example.
Ideally, you can fork the [Stackblitz starter template](https://stackblitz.com/edit/vue3-openlayers-template)
