### ISSUE TITLE
Flowline or multicolor multi-line-string ?

### ISSUE THREAD

**Issue by signmeuptwice** [MelihAltintas/vue3-openlayers#33]
I cannot see in the doc an example of a multicolor linestring 

the closest I fount is the `multi-line-string` so I tried this

          <ol-feature v-if="waypoints && waypoints.length > 0">
            <ol-geom-multi-line-string :coordinates="waypoints"></ol-geom-multi-line-string>
            <ol-style :overrideStyleFunction="overrideStyleFunction">
              <ol-style-stroke color="green" :width="7"></ol-style-stroke>
            </ol-style>
          </ol-feature>

problem is that my `overrideStyleFunction` is only triggered once and the line is the same color everywhere
not sure what I am doing wrong

OL has `Flowline` which could be great to have as a component ?

**Comment by signmeuptwice** [comment]
I tried installing ol-ext but I got from 5 to 31 vulnerabilities and multiple warnings so I will pass
If there is no solution with multi string I can only create many points instead ? or small lines ?

**Comment by MelihAltintas** [comment]
update 0.1.46 I added example usage to demo page 
https://vue3openlayers.netlify.app/demo/
<ol-style-flowline color="red" color2="yellow" :width="10" :width2="10" :arrow="1" />

**Comment by signmeuptwice** [comment]
@MelihAltintas Thank you for the updated example
I spent quite some time on it and I think there was miscommunication

I need to be able to display elevation; so what is needed is being able to set color per point/line/divider

The flowline I mentioned from `ol-ext` takes this into account with a third parameter in the array [x,y,z] normally but yours is just a style with a gradient between two colors as far as I can tell ? Tried adding color3 with no effect

I tried integrating it in a <ol-style> and applied a styleFunction with just a console log
same problem as before it is only executed once so that does not solve the issue.

Is it possible to display elevation somehow ?

**Comment by MelihAltintas** [comment]
you can give a function to color with 0.1.47. f=feature s=step
```
      <ol-style-flowline :color="flowLineColor" :width="10" />

        const getRandomColor = () => {
            var letters = '0123456789ABCDEF';
            var color = '#';
            for (var i = 0; i < 6; i++) {
                color += letters[Math.floor(Math.random() * 16)];
            }
            return color;
        }
        const flowLineColor = (f, step) => {
            console.log(f, step)
            return getRandomColor(); // or give color according to feature(f) properties.
        }
```

**Comment by signmeuptwice** [comment]
@MelihAltintas Thank you for the enhancements; I am very much looking forward to using this 👍 

However there seems to be two issues with the current revision:
- first the step is outputing values between 0 and 1 which makes it hard to match to a data array. Can you output index too ? or simply carry extra data or specify input format and avoid discarding extra data from array? my data is in the form of [x,y,z,d,c] but in the style function I cannot see the extra data in feature.

- then I first began with a console log and it seems that it is looping many times over the same lineString from what I can tell; this might break an array data matching from my tryouts. It took a good 5seconds to console log steps and 20 for features in the console; I experienced a big slowdown so this could be a big performance hit; do you have the same behavior ?

I you need I can share my entire component

**Comment by signmeuptwice** [comment]
@MelihAltintas hey, did you receive my last message ? Being able to display altitude is very important to my project; not sure what to do. Thank you
