### ISSUE TITLE
OlInteractionDragbox component is missing in the build

### ISSUE THREAD

**Issue by SezerYardim** [MelihAltintas/vue3-openlayers#335]
**Describe the bug**
No `OlInteractionDragbox` component  

**Affected version(s)**

Please run `npm list --depth=0 vue vue3-openlayers ol ol-ext ol-contextmenu` and paste the output below:

```
├── ol-contextmenu@5.4.0
├── ol-ext@4.0.18
├── ol@8.2.0
├── vue@3.4.21
└── vue3-openlayers@4.1.2

```

**To Reproduce**

1. Go to "/node_modules/vue3-openlayers/dist/components/interaction/index.d.ts"
2. Check OlInteractionDragbox component is there

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 14]
- OS: [e.g. iOS 16.15.1]

**Additional context**

**Comment by d-koppenhagen** [comment]
`OlDragBoxInteraction` has been released with version 6.3.0. Please checkout the [Changelog](https://github.com/MelihAltintas/vue3-openlayers/blob/main/CHANGELOG.md).
Note: With version 8.0.0 which was just released, it has been renamed to `OlInteractionDragbox` (as described in the docs).
Please update to the latest version. Breaking Changes are described in the Changelog for migration.
The docs are always aligned with the latest published version of this lib.
