### ISSUE TITLE
Delete Geometries After Draw Or Any Other Geometries

### ISSUE THREAD

**Issue by ibrahim-developper** [MelihAltintas/vue3-openlayers#34]
When implement **ol-interaction-draw**  how i can add feature to user delete the selected shape ,
i'm try from **ol-interaction-clusterselect** get the featureSelected event and if have a function to delete the current element or something like that or please if have some other way.

Thank you.

**Comment by MelihAltintas** [comment]
You can give the ref to ol-source-vector then with this ref you can call removeFeature(deletedFeature) method

**Comment by ibrahim-developper** [comment]
> You can give the ref to ol-source-vector then with this ref you can call removeFeature(deletedFeature) method

Thank you alot how get this parsmeter

**Comment by ibrahim-developper** [comment]
> You can give the ref to ol-source-vector then with this ref you can call removeFeature(deletedFeature) method

Thank you a lot, how get this parameter deletedFeature 
Thank you again.

**Comment by ibrahim-developper** [comment]
1- i add ref attribute to  ol-source-vector **<ol-source-vector ref="mapvector" :projection="projection">** 
 2- when click to the marker then delete marker i get the featureSelected and pass it to **this.$refs.mapvector.removeFeature(featureSelected )**
but give me this error

this.$refs.mapvector.removeFeature is not a function


![image](https://user-images.githubusercontent.com/52491316/133578829-0e5806db-0182-4968-b548-924824665cd5.png)

**Comment by MelihAltintas** [comment]
Mapvector has source
this.$refs.mapvector.source. removeFeature(featureSelected

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ibrahim-developper** [comment]
> Mapvector has source this.$refs.mapvector.source. removeFeature(featureSelected) Please use console log for viewing fileds and methods :)

Thank you a lot

**Comment by MelihAltintas** [comment]
you can give a star if you like it :)
