### ISSUE TITLE
When I install on my project

### ISSUE THREAD

**Issue by metaKHT** [MelihAltintas/vue3-openlayers#340]
when I do ' npm i '

src/main.ts:45:9 - error TS2345: Argument of type '{ install: FunctionPlugin<any[]>; }' is not assignable to parameter of type 'Plugin<[]>'.
  Type '{ install: FunctionPlugin<any[]>; }' is not assignable to type 'FunctionPlugin<[]>'.
    Type '{ install: FunctionPlugin<any[]>; }' is not assignable to type '(app: App<any>) => any'.
      Type '{ install: FunctionPlugin<any[]>; }' provides no match for the signature '(app: App<any>): any'.

45 app.use(OpenLayersMap);
           ~~~~~~~~~~~~~
           
         I can't use it.

**Comment by d-koppenhagen** [comment]
pleas give more context for investigation:
- Vue Version
- Vite / other Bundler version, used plugins, etc.

**Comment by d-koppenhagen** [comment]
I will close this issues since there was no response. Please re-open with detailled information for reproduction of your issue if it still exists and verify it with the latest version.
