### ISSUE TITLE
composables/useOpenLayersEvents.ts can not get getCurrentInstance without setup function

### ISSUE THREAD

**Issue by DLinser** [MelihAltintas/vue3-openlayers#342]
**Describe the bug**
It it normal first time. But something wrong happend in the event function like the 'watch'.It is return null

**Comment by d-koppenhagen** [comment]
Please provide a minimal reporduction repo / stackblitz project to be able to investigate.

**Comment by DLinser** [comment]
just like this demo
`<ol-source-vector :projection="projection">
        <ol-interaction-draw
          v-if="drawEnable"
          :type="drawType"
          @drawend="drawend"
          @drawstart="drawstart"
        >
          <ol-style>
            <ol-style-stroke
color="blue" :width="2" />
            <ol-style-fill color="rgba(255, 255, 0, 0.4)" />
          </ol-style>
        </ol-interaction-draw>
      </ol-source-vector>`
![企业微信截图_17143719181601](https://github.com/MelihAltintas/vue3-openlayers/assets/31381894/e9fb775f-ea26-47a3-adb9-290a9997eb6b)

the getCurrentInstance in 'composables/useOpenLayersEvents.ts' does not effect when you want to change drawType

**Comment by d-koppenhagen** [comment]
probably related to #361

**Comment by d-koppenhagen** [comment]
should be fixed with #361
