### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by oguzhankidik** [MelihAltintas/vue3-openlayers#350]
i have vue 3 project. uses webpack and laravel mix. I cant use this library on my project. 

package.json
```
"ol": "^9.1.0",
"ol-contextmenu": "^5.4.0",
"ol-ext": "^4.0.18",
"vue3-openlayers": "^9.0.0",
```

app.js

```
import 'vue3-openlayers/styles.css';
import OpenLayersMap from 'vue3-openlayers';
app.use(OpenLayersMap /*, options */);

```

i installed library with no problem. but i got 90 errors when i run the project. errors are like these
![image](https://github.com/MelihAltintas/vue3-openlayers/assets/86284623/929060f5-29ff-41ea-a532-85878296adf7)

**Comment by d-koppenhagen** [comment]
Hey @oguzhankidik would you like to share your solution/ what was wrong?

**Comment by oguzhankidik** [comment]
> Hey @oguzhankidik would you like to share your solution/ what was wrong?
i added these lines to webpack.config.js. 

```
module: {
        rules: [
            {
                test: /\.m?js$/,
                resolve: {
                    fullySpecified: false,
                },
            },
        ],
    },
```
