### ISSUE TITLE
add style to the interraction-draw has no effect

### ISSUE THREAD

**Issue by 94ashui** [MelihAltintas/vue3-openlayers#351]
**Describe the bug**
![image](https://github.com/MelihAltintas/vue3-openlayers/assets/89236888/34b43c31-b03b-413c-9b41-28bc56594651)

(https://stackblitz.com/edit/vue3-openlayers-template-rk19qn?file=package.json,src%2Fcomponents%2FTheMap.vue)

**Comment by d-koppenhagen** [comment]
In your demo you are using `"vue3-openlayers": "^1.2.0"`. Can you please update / provide an example for reporduction with the latest major version. Please check if the problem still exists.

**Comment by d-koppenhagen** [comment]
It should works as shown in the Demo here: https://vue3openlayers.netlify.app/componentsguide/interactions/draw/#usage

**Comment by d-koppenhagen** [comment]
I managed to find a problem even in the latest version. I fixed it and published version 9.0.1
