### ISSUE TITLE
Overlays does not display since 9.0.0

### ISSUE THREAD

**Issue by ElysaSrc** [MelihAltintas/vue3-openlayers#352]
**Describe the bug**

Since version 9.0.0 overlay display. We can also see this on the documentation: https://vue3openlayers.netlify.app/componentsguide/overlay/#example-1-overlay-content

Example 1 is empty.

**Affected version(s)**

All version over 9.0.0

**Expected behavior**

Overlay items should be displayed.

**Comment by d-koppenhagen** [comment]
Oh, it seems like the wrong default value is passed for `className`. Please set it to `ol-overlay-container ol-selectable`. I will fix this meanwhile and release the fix with the next version

**Comment by d-koppenhagen** [comment]
Released with 9.0.2: https://github.com/MelihAltintas/vue3-openlayers/releases/tag/v9.0.2

**Comment by ElysaSrc** [comment]
Thank you very much !

**Comment by ElysaSrc** [comment]
There is another issue with the current update : events are not propagated when there is an overlay. If you do a scroll with your mousewheel on an overlay, the event does not propagate like it used to, and the zoom is not modified.

**Comment by d-koppenhagen** [comment]
This could be because `stopEvent` is set to `true` by default which was a breaking change and introduced to align with the OpenLayers API.

**Comment by d-koppenhagen** [comment]
Please raise new Issues if you find more. Thanks! :)
