### ISSUE TITLE
OlWebglVectorLayer doesn't react to `visible`

### ISSUE THREAD

**Issue by pwuertz** [MelihAltintas/vue3-openlayers#355]
There was a problem with `OlVectorLayer` not reacting to `visible` (issue #347), which was fixed in commit 22928f929791819757b1a7fafc8e18f2392337a4.

`OlWebglVectorLayer` seems to be affected by the same issue and presumably requires a similar fix?

**Comment by d-koppenhagen** [comment]
What version are you using?

**Comment by pwuertz** [comment]
Most recent release, `10.0.0`.
