### ISSUE TITLE
Events of "ol-source-image-wms" element.

### ISSUE THREAD

**Issue by Dmitriy0123456** [MelihAltintas/vue3-openlayers#365]
Hello!
I have problems handling "ol-source-image-wms" element events.
```
<template v-for="points in pointsList">
    <ol-image-layer>
      <ol-source-image-wms
        :params="points.params"
        :url="points.url"
        :layers="points.layer"
        serverType="geoserver"
        @change="changeHandler"
        @error="errorHandler"
        @imageloadend="imageloadendHandler"
        @imageloaderror="imageloaderrorHandler"
        @imageloadstart="imageloadstartHandler"
        @propertychange="propertychangeHandler"
      ></ol-source-image-wms>
    </ol-image-layer>
  </template>
```

I can't intercept events: "change", "error", "imageloadend", "imageloaderror", "imageloadstart", "propertychange".
I have used different naming conventions.

Dependencies:
- vue@3.4.31
- ol@9.2.4
- vue3-openlayers@10.0.2

I need to know the start and end points of the image upload.
I would be grateful for any help. Thank you very much.

**Comment by nicokruger** [comment]
Just a note to add +1 - we are experiencing the same on OlSourceTileWms - no events (tileloadstart, tileloadend, etc) are being received when we attempt:


`
  <Layers.OlTileLayer v-for='xxxxx' :key='yyyy'>
       <Sources.OlSourceTileWms
           :url="baseUrl+'/geoserver/wms'"
           :layers="layer.layer"
           serverType="geoserver"

           @tileloadstart='onTest'
           @tileloadend='onTest'
           @tileloaderror='onTest'

         />
  </Layers.OlTileLayer>
`

Is this supposed to be supported at the moment, these events explicitly?

**Comment by nonlinearcom** [comment]
Hi, same here with vector tiles, `onTileLoadStart` and `onTileLoadEnd` not being triggered:

```js
  <ol-vector-tile-layer
      ref="vectorTileLayerRef"
      :preload="3"
    >
      <ol-source-vector-tile
        :url="mapboxVectorTileUrl"
        :format="mvtFormat"
        @tileloadstart="onTileLoadStart"
        @tileloadend="onTileLoadEnd"
        @tileloaderror="onTileLoadEnd"
      >
        <ol-style
          :override-style-function="styleFunction"
        />
      </ol-source-vector-tile>
    </ol-vector-tile-layer> 
 ```
 
I found a temporary workaround by adding the event listeners `onMounted`:

```js
onMounted(() => {
  // Temp workaround for tile load events
  const vectorTileSource = vectorTileLayerRef.value.vectorTileLayer.getSource()
  vectorTileSource.on('tileloadstart', onTileLoadStart)
  vectorTileSource.on('tileloadend', onTileLoadEnd)
  vectorTileSource.on('tileloaderror', onTileLoadEnd)
})
