### ISSUE TITLE
how can I use it by cdn?

### ISSUE THREAD

**Issue by qianYzz** [MelihAltintas/vue3-openlayers#367]
I want import it by cdn。

**Comment by qianYzz** [comment]
![image](https://github.com/user-attachments/assets/5b4bccc1-9b3a-4ebd-a0d0-a86d04b956d4)

**Comment by qianYzz** [comment]
I don`t know is it right?

**Comment by d-koppenhagen** [comment]
Hey, would you mind to share how you solved it, so I can include it in the documentation?

**Comment by qianYzz** [comment]
> Hey, would you mind to share how you solved it, so I can include it in the documentation?

you can see Image above。fires image is my enter file，second image is vite.config.ts。last is use；

**Comment by d-koppenhagen** [comment]
But you only consume vue via cdn, not vue3-openlayers don't you?

**Comment by qianYzz** [comment]
> But you only consume vue via cdn, not vue3-openlayers don't you?

yes

**Comment by qianYzz** [comment]
> But you only consume vue via cdn, not vue3-openlayers don't you?

you mean vue3-openlayers  contain vue？do`t need import Vue？
