### ISSUE TITLE
#370 is not fixed

### ISSUE THREAD

**Issue by fbatschi** [MelihAltintas/vue3-openlayers#371]
**Describe the bug**
Unfortunately there is no way to reopen a issue, so i have to do a new one.

#370 seems not fixed to me. The commit https://github.com/MelihAltintas/vue3-openlayers/commit/91a07cac37d7a579014bc0bcc7deae7e226237c5 is probably not working, since there is a `!` to much in it.

Also, the warning ` Modify interactions needs either a either a source or features to work` has a `either a` too much.

**Affected version(s)**

11.1.0

**To Reproduce**

1. Include a `<ol-interaction-modify>` in a <ol-source-vector> without a `'features' key.

**Expected behavior**

- `<ol-interaction-modify>` without `features` works inside a `<ol-source-vector>`
- `<ol-interaction-modify :features="foo">`  works outside a `<ol-source-vector>`
 
without warnings.

**Comment by MatthieuGomes** [comment]
Still not fixed

**Comment by d-koppenhagen** [comment]
Since this issue was closed month ago and a "Still not fixed" description is not very helpful, I would encourage you to open a new issue with a detailed description and notes about used versions (as requested in the issue template)

**Comment by MatthieuGomes** [comment]
> Since this issue was closed month ago and a "Still not fixed" description is not very helpful, I would encourage you to open a new issue with a detailed description and notes about used versions (as requested in the issue template)

Okay, will do that
