### ISSUE TITLE
The warning regarding ol-tile-layer displayed in the browser.

### ISSUE THREAD

**Issue by makerForAll** [MelihAltintas/vue3-openlayers#388]
When I use the ol-tile-layer tag, the following warning appears in the browser.

<img width="743" alt="截屏2024-10-19 10 14 39" src="https://github.com/user-attachments/assets/5db603a0-8607-4e70-beb6-3a46933c7769">

----

https://github.com/makerForAll/vue-webgis-project

**Comment by d-koppenhagen** [comment]
fixed with version 11.3.0
