### ISSUE TITLE
Can't install using Yarn

### ISSUE THREAD

**Issue by azygis** [MelihAltintas/vue3-openlayers#391]
**Describe the bug**
We can't seem to install the package using Yarn as our package manager. Kinda resurrecting the #273.

I removed the whole bug template just because I've made a (non-)working StackBlitz fork: https://stackblitz.com/edit/vue3-openlayers-template-rxpyy8?file=package.json

**Comment by d-koppenhagen** [comment]
Please update the vue version. When I fork your template and update to Vue@3.5.13, it works:
https://stackblitz.com/edit/vue3-openlayers-template-amgpph2q?file=package.json
