### ISSUE TITLE
useSource - "toRefs() expects a reactive object but received a plain one" warning

### ISSUE THREAD

**Issue by szwjonks** [MelihAltintas/vue3-openlayers#393]
**Describe the bug**
Vue warns about using toRefs on object which isn't reactive. It happens for some sources, e.g.: WMS/WMTS and I think it's because props are descructured like [here](https://github.com/MelihAltintas/vue3-openlayers/blob/main/src/components/sources/OlSourceWmts.vue#L83)

**Affected version(s)**

11.2.0

**To Reproduce**
Check stakblitz with example copied from docs - https://stackblitz.com/edit/vue3-openlayers-template-du4aja?file=src%2Fcomponents%2FTheMap.vue

**Expected behavior**
No warnings in console, no possible troubles connected with those warnings.

**Screenshots**
![obraz](https://github.com/user-attachments/assets/05df3602-6f53-4599-ac73-112357596d63)

**Additional context**
Warning about deleting cacheSize also is in console, but it's have separate [issue](https://github.com/MelihAltintas/vue3-openlayers/issues/388)

**Comment by azygis** [comment]
I was _just_ about to post about this! Thanks for taking it over!

**Comment by ahmadem** [comment]
Hi.
I also encounter this problem when I try to use it in Quasar.

**[Vue warn] Delete operation on key "cacheSize" failed: target is readonly.**
