### ISSUE TITLE
Question: What is the preview prop on ol-vector-layer?

### ISSUE THREAD

**Issue by eric-g-97477** [MelihAltintas/vue3-openlayers#395]
In the demo code, I see:
```
    <ol-vector-layer
      title="AIRPORTS"
      preview="https://raw.githubusercontent.com/MelihAltintas/vue3-openlayers/main/src/assets/tr.png"
    >
```

Looking at the documentation on [ol-vector-layer properties](https://vue3openlayers.netlify.app/componentsguide/layers/vectorlayer/#properties), I don't see the `preview` prop mentioned. 

I don't see any mention of `preview` in the OpenLayers documentation either.

I was wondering what it was for or what it did. Perhaps resolving this ticket could involve updating the documentation.

**Comment by d-koppenhagen** [comment]
Hey, I added it to the docs. its used by the layerswitcherimage control: https://vue3openlayers.netlify.app/componentsguide/mapcontrols/layerswitcherimage/

**Comment by eric-g-97477** [comment]
Since it is a property of ol-vector-layer, shouldn't it be mentioned there?

**Comment by d-koppenhagen** [comment]
Probably. But it's a property on every layer type. And it's only evaluated by the control which comes originally from ol-ext and checks for this preview option set on a layer.
So what I want to say: no need to add it if you don't use this control. And if you use it, it's documented there.
