### ISSUE TITLE
MapboxVectorLayer 

### ISSUE THREAD

**Issue by bdiouih** [MelihAltintas/vue3-openlayers#398]
First of all, thank you for this excellent  library.

How to use MapboxVectorLayer  from 'ol-mapbox-style' as a layer in this library?
Sorry if the answer is obvious, but I did not find a hint in the documentation.

**Comment by d-koppenhagen** [comment]
Hey, there is currently not mapbox layer or style from this lib.
Feel free to extend the lib and create a plugin:

https://vue3openlayers.netlify.app/pluginsguide/

**Comment by bdiouih** [comment]
Thank you for your answer.
Sorry, but the documentation does not seem trivial, with errors like:

Failed to resolve import "@/composables/useLayer"
(replaced @ with vue3-openlayers with no luck)

I would appreciate if anyone could provide some working MapboxVectorLayer integration code.

Thank you
