### ISSUE TITLE
(request) - features parameter for the Modify & Select interaction

### ISSUE THREAD

**Issue by akc4** [MelihAltintas/vue3-openlayers#4]
I would like to suggest the `features` parameter for the `Modify` interaction.

Currently if a feature is selected to enable the Modify interaction, all the features present in an array would be added to the Modify `features` parameter.

if I understand correctly the `features` parameter on the Modify interaction allows to select which features can be modified.

In this example, if one country is selected to enable the `editEnable`, they would all be editable.

```
      <ol-vector-layer>
        <ol-source-vector :url="'https://openlayers.org/en/latest/examples/data/geojson/countries.geojson'" :format="geoJsonFormat" :projection="data.projection">
          <ol-interaction-modify v-if="editEnable" @modifyend="modifyend" @modifystart="modifystart"> </ol-interaction-modify>
          <ol-interaction-snap v-if="editEnable" />
        </ol-source-vector>
      </ol-vector-layer>
      <ol-interaction-select @select="featureSelected" :condition="selectCondition">
        <ol-style>
          <ol-style-stroke :color="'red'" :width="2"></ol-style-stroke>
          <ol-style-fill :color="`rgba(255, 0, 0, 0.4)`"></ol-style-fill>
        </ol-style>
      </ol-interaction-select>
```

EDIT:
If possible to add the `features` parameter on the Select Interaction as well.

**Comment by MelihAltintas** [comment]
you can update your version to 0.1.25 :)
