### ISSUE TITLE
Can i use TypeScript？

### ISSUE THREAD

**Issue by hedongshu** [MelihAltintas/vue3-openlayers#42]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

openlayer 已经有 @types/ol ,但是 vue3-openlayers不能使用它

现在vue3-openlayers内是通过 provide ， inject来获取。但是这样没有类型了
    app.provide('ol-feature',feature)
    app.provide('ol-geom',geom)
    app.provide('ol-animations',animations)
    app.provide('ol-format',format)
    app.provide('ol-loadingstrategy',loadingstrategy)
    app.provide('ol-selectconditions',selectconditions)
    app.provide('ol-extent',extent)

我要怎么做才能在const selectConditions = inject('ol-selectconditions')   获取到selectConditions的类型呢

**Describe alternatives you've considered**

**Additional context**

**Comment by MelihAltintas** [comment]
No only support js
