### ISSUE TITLE
getTileGrid  in ol-source-wmts 

### ISSUE THREAD

**Issue by 604587986** [MelihAltintas/vue3-openlayers#44]
getTileGrid  in ol-source-wmts is a computed value ,but my project has a error 'Unknown TILEMATRIX' , i think if getTileGrid can be a prop

**Comment by 604587986** [comment]
maybe resolutions and matrixIds should be props

**Comment by MelihAltintas** [comment]
can you share examples in code sandbox or code examples for recreating the issue.
