### ISSUE TITLE
Simplify interactions by events on geometries

### ISSUE THREAD

**Issue by iBobik** [MelihAltintas/vue3-openlayers#49]
**Is your feature request related to a problem? Please describe.**
Using interactions are super difficult to learn - it does not make sence to use another component, wire it by callback and properties to just make onClick on an geometry. Or specifically, it makes sence only to devs who have OL internals in mind. ;-)

**Describe the solution you'd like**
Offer set of events, props on geometries or featues itself as it is usual in Vue ecosystem.
```
<ol-view @click="hoverPlace = false">
...
        <ol-feature v-for="place in places" @hover="hoverPlace = place.id" @click="selectedPlace(place.id)">
          <ol-geom-point :coordinates="fromLonLat(place.lonLat)" />
          <ol-style :z-index="place.type === 'ln_verified' ? 10 : 1">
            <ol-style-icon src="assets/ln_marker.svg" :scale="hoverPlace === place.id ? 0.1 : 0.05" />
          </ol-style>
        </ol-feature>
...
selectedPlace (place) {
  $router.push('/place/' + place)
}
```

Example form Mapbox: https://v-mapbox.geospoc.io/api/marker.html#events

**Describe alternatives you've considered**
Use any other library what offers simpler aproach in Vue - used Leaflet and MapboxJS, both are easy to use.

**Comment by MelihAltintas** [comment]
Thanks for your suggestions. But OpenLayers structure doesn't support this event.  https://openlayers.org/en/latest/apidoc/module-ol_Feature-Feature.html Feature does not send and event when the selected :)
