### ISSUE TITLE
Map not visible after v-show

### ISSUE THREAD

**Issue by signmeuptwice** [MelihAltintas/vue3-openlayers#53]
"vue3-openlayers": "0.1.*",

Hiding the map with `v-show` results in a blank canvas and error message `[Warning] No map visible because the map container's width or height are 0. (vue-0eab179a9c5c1648c422.js, line 51744)` when show = true

Not sure what to do about this; is this a bug or is there something to do ?

```
<ol-map
        ref="olMap"
        :key="uid+'-map'"
        class="ol-map-wrapper"
        :default-interactions="interactionOptions"
        style="height: 350px; width: 720px"
        v-on:mousedown="disableUpdate"
        v-on:mouseup="enableUpdate"
    >
```

calling `olMap.value.map.updateSize()` solves the visibility issue but I still have the warning

**Comment by MelihAltintas** [comment]
I could not reproduce this. There is no error in the console when the visibility changed.

You can review my example :https://codesandbox.io/s/v-show-warning-yvk7b?file=/src/components/Comp.vue
