### ISSUE TITLE
TileGrid Support

### ISSUE THREAD

**Issue by lisarx** [MelihAltintas/vue3-openlayers#63]
Hey all!
Thanks for providing this library, it makes our work with Vue and OL a lot easier!
But - is there any reason that you don't support the TileGrid for SourceXYZ?

We need it for our project and I've already included it in a local version, but it would be cool if you could provide the support officially as well. If you want, I can make a pull request with our local version. :)

**Comment by MelihAltintas** [comment]
of course you can make a pull request :) I would be very happy if there is interest in the project and people support the development.

**Comment by lisarx** [comment]
Thank you! I starred and made the PR - Closing this now. :)
