### ISSUE TITLE
wrong type in overlay Positioning

### ISSUE THREAD

**Issue by dc-z** [MelihAltintas/vue3-openlayers#66]
**Describe the bug**
https://vue3openlayers.netlify.app/componentsguide/overlay/#positioning
positioning
Type: string
Default: top-left

BUT
:positioning await ARRAY.
working: :positioning="['top-left']" // or const positioning = ref(['top-left'])
**not working: :positioning="'top-left'" // or const positioning = ref('top-left')** 

**To Reproduce**
just try a component

**Expected behavior**

expected the right is like **not workin**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
https://github.com/MelihAltintas/vue3-openlayers/blob/main/src/components/map/Overlay.vue

...
positioning: {
            type: Array
        },
...

**Comment by MelihAltintas** [comment]
position type has already array. Documentation is wrong :) I will update. Thanks for your report. If you like the project please give a star :)
