### ISSUE TITLE
Unselect Feature

### ISSUE THREAD

**Issue by wiese42** [MelihAltintas/vue3-openlayers#67]
How can I unselect a feature programmatically?

**Comment by MelihAltintas** [comment]
You should give a ref to select interaction then you can remove selected features with this code:
`   selectInteraction.value.select .getFeatures() .clear();`

Example :https://codesandbox.io/s/unselect-programaticly-dtgvvs?file=/src/components/Comp.vue

If you like this lib, please give a star for motivation :)

**Comment by wiese42** [comment]
Thanks a lot. Star is earned and on its way.
