### ISSUE TITLE
Usage in a component render function

### ISSUE THREAD

**Issue by ymarcon** [MelihAltintas/vue3-openlayers#69]
Hi,

I would like to render the "ol-map" (and its children components) using the `h()` function. Something like:

```
h(Map, {
    class: 'q-mt-md',
    loadTilesWhileAnimating: true,
    loadTilesWhileInteracting: true,
    style: 'height:400px'
  }, [ 
      h(View, {
          center: [0, 45],
          rotation: 0,
          zoom: 8,
          projection: 'EPSG:4326'
      }),
      h(FullScreenControl),
      h(TileLayer, null, [ h(SourceOSM) ])
  ])
```

What is the appropriate `import` directive that I could use to get access to the component definitions Map, View, FullScreenControl, TileLayer etc. ?

Thanks

**Comment by MelihAltintas** [comment]
Example usage: https://codesandbox.io/s/render-example-kl0qs?file=/src/App.vue:0-636

```
<script setup>
import { h, defineComponent } from "vue";
import { Map, MapControls, Layers, Sources } from "vue3-openlayers";

export default defineComponent({
  render() {
    return h(
      Map.Map,
      {
        class: "q-mt-md",
        loadTilesWhileAnimating: true,
        loadTilesWhileInteracting: true,
        style: "height:400px",
      },
      [
        h(Map.View, {
          center: [0, 45],
          rotation: 0,
          zoom: 8,
          projection: "EPSG:4326",
        }),
        h(MapControls.FullScreenControl),
        h(Layers.TileLayer, null, [h(Sources.SourceOSM)]),
      ]
    );
  },
});
</script>
```

**Comment by ymarcon** [comment]
Nice thank you, it is starred :)

Almost there, I have an error with the Interactions:
https://codesandbox.io/s/render-example-forked-vb7mzz?file=/src/App.vue

**Comment by ymarcon** [comment]
It looks like both `Interactions` and `Animations` are not exported:
https://github.com/MelihAltintas/vue3-openlayers/blob/main/src/index.js#L55

**Comment by MelihAltintas** [comment]
thanks for your report. Please update 0.1.63. I fixed it
