### ISSUE TITLE
Source change on modify & stopClick parameter on draw interaction

### ISSUE THREAD

**Issue by akc4** [MelihAltintas/vue3-openlayers#7]
in the following example using the `draw interaction` with the my generated features. If I draw a polygon and then click on another polygon to select it and modify it, the drawn one disappears because the source changes.

However when using the `:url` features if you draw a polygon and then select a country and modify it, the drawn polygon doesn't disappear.

So if I understand correctly, if I want the source to remain the same I must use the `:url` instead of `:features` parameter to load features?

Also the `stopClick` on the parameter on the `draw interaction` doesn't seem to work, it still fires the click event.

https://codesandbox.io/s/vue3-openlayers-forked-qqrqx?file=/src/App.vue:807-816

**Comment by MelihAltintas** [comment]
i did not catch the issue because in your example drawn polygon does not disappear after the select another feature. but your feature select function algorithm is wrong because after the first selection, other selections has a deselect array and modifyEnabled is always false. So change the featureSelect function:

```
    function featureSelected(event) {
      modifyEnabled.value = false
      if (event.selected.length > 0) {
        modifyEnabled.value = true
      }
    }

```

**Comment by akc4** [comment]
Thank you for your reply.

As for the `stopClick` parameter on the `draw interaction`, I thought when it is set to `true` it stop's the click/singleclick/doubleclick events. So the `select interaction` shouldn't be fired.

**Comment by MelihAltintas** [comment]
thanks for detailed explanation. it is related to OpenLayers this issue https://github.com/openlayers/openlayers/issues/11891  I used 6.5.0 version and I update to openlayers to 6.6.1. you can use 0.1.27 version for fix this issue
