### ISSUE TITLE
Spam email promoting this repository

### ISSUE THREAD

**Issue by MalteT** [MelihAltintas/vue3-openlayers#70]
**Describe the bug**
I received the following email, promoting this repository. And while the work being done here looks good (keep it up!),
I consider the received email spam. I'm wondering why I would receive such an email and who would send such an email.

**To Reproduce**
1. Exist
2. Receive a strange email

**Expected behavior**
No promotional email should end up in my inbox.

**Screenshots**
![image](https://user-images.githubusercontent.com/11077981/156134998-f2850745-87ed-490a-8dbc-8a06284727b0.png)

**Comment by MelihAltintas** [comment]
If you have stated that you want to receive notifications about the library on any site, this e-mail is sent automatically. Your name will be removed from the mailing list. Sorry for the inconvenience.
