### ISSUE TITLE
Slow zooming when zoom has a reactive variable and zoomChanged is listened

### ISSUE THREAD

**Issue by supermarcos** [MelihAltintas/vue3-openlayers#71]
**Describe the bug**
I detected an odd behavior when I tried to connect a state management system (vuex, pinia...):
Here is my view:
` <ol-view
        ref="view"
        :center="center"
        :zoom="appStore.getMapZoomLevel()"
        @zoomChanged="zoomChanged"
        />
`
The only thing the store getter `getMapZoomLevel()` is just returning the value:
`
getMapZoomLevel() {
  return this.mapZoomLevel;
},
`
And the action to set it:
` 
setMapZoomLevel(zoomLevel) {
   this.mapZoomLevel = zoomLevel;
},
`
I listen to the change event like such:
`
function zoomChanged(newzoom) {
  console.log(newzoom);
  appStore.setMapZoomLevel(newzoom);
}
`
And I see non-integers numbers being dumped on the console and the scroll (using the mouse wheel) is veeery slow. It doesn't move by integers, that's what I mean.

You can reproduce it much simpler without state management system, just a reactive variable in zoom prop. Follow the steps in "To Reproduce" section:

**To Reproduce**
1. Declare a very simple map with nothing (no need)
2. Declare `const zoom = ref(10)` and use zoom in zoom prop (`:zoom="zoom"`)
3. Listen to the zoomChanged event: `@zoomChanged="zoomChanged"`
4. Create `zoomChanged` function: `function zoomChanged(newzoom) { zoom.value = newzoom; }`
5. Scroll back and forth with the mouse wheel and observe what happens... very slow behavior.

**Expected behavior**
As fast (or normal) as it behaves when there is no reactive variable being used.

Maybe I'm missing something, but with this behavior I wouldn't be able to share the zoom level on a global state and being able to zoom in and zoom out using external components by changing this value, which, I think, should be possible.

Am I missing something and doing it all wrong?
Thank you!
:)

**Comment by MelihAltintas** [comment]
Hello,

Zoom probe should be used for the first value, if you assign the change to it again, you will create a cyclic dependency. (Because zoom prop change then zoomChanged event fired again)You should hold another data field like a currentZoom then you change this value.

https://codesandbox.io/s/zoom-demo-dj5cvv?file=/src/components/Comp.vue
