### ISSUE TITLE
After losing connection, random tiles stop updating.

### ISSUE THREAD

**Issue by mdezelak** [MelihAltintas/vue3-openlayers#72]
**Describe the bug**
Map fails to process 'white' tiles if user loses connection mid usage.

**To Reproduce**
1. Go to https://vue3openlayers.netlify.app/componentsguide/map/
2. Zoom to random spot on map.
3. Disable internet connection
4. Move around the map. 
5. White tiles begin to load.
6. Re-connect, rest of the map starts working again, white tiles remain white. 

**Expected behavior**
White tiles should initiate new call for source img.
Can't reproduce bugs on official openlayers examples.

**Screenshots**
![image](https://user-images.githubusercontent.com/16761483/159025241-e08e0966-2344-43d7-b9e6-639b43616bda.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: chrome

**Comment by d-koppenhagen** [comment]
@mdezelak I think it works as expected doesn't it? When network is disabled and you start zoom-in / zoom-out, ol tries to retrieve some tiles that aren't already rendered / cached from the network. This causes of cause white tiles as there is no response.
In my opinion, we can't handle this better.
For temp. connect. problem, you can configure your server delivering the tiles to send a cache header. This will at least display "old" tiles when already loaded once, but it won't solve the network problem.

Please re-open this issue, when you have other information / opinions.
