### ISSUE TITLE
Is it possible to assign style to particular features inside an animated cluster layer?

### ISSUE THREAD

**Issue by supermarcos** [MelihAltintas/vue3-openlayers#76]
**Is your feature request related to a problem? Please describe.**
I'm not sure. I tried to find an example where I can assign individual styles to geo-points regarding some attribute of those points (say you have a map with geo-points and they are color-coded depending if there's an issue in such place), but if they're inside an animated clusterlayer the layer style is defining the style, but the geo point doesn't seem to be able to get it individually.

**Describe the solution you'd like**
Doing it this way doesn't work:
It will take the styles of the animation layer, but if I remove it and leave only the style in the feature, it won't take any style at all.
```
<ol-animated-clusterlayer :animationDuration="500" :distance="40">
        <ol-source-vector ref="vectorsource">
          <ol-feature v-for="site in geopoints" :properties="{name: site.name}">
            <ol-geom-point
                :coordinates="fromLonLat(site.coordinates, projection.value)"
            ></ol-geom-point>
            <ol-style v-if="site.id == 8">
              <ol-style-circle :radius="radius">
                <ol-style-fill :color="fillColor"></ol-style-fill>
                <ol-style-stroke :color="strokeColor" :width="strokeWidth"></ol-style-stroke>
              </ol-style-circle>
            </ol-style>
          </ol-feature>
        </ol-source-vector>

        <ol-style :overrideStyleFunction="overrideStyleFunction">
          <ol-style-stroke color="red" :width="2"></ol-style-stroke>
          <ol-style-fill color="rgba(255,255,255,0.1)"></ol-style-fill>

          <ol-style-circle :radius="20">
              <ol-style-stroke color="rgba(255,255,255,0.1)" :width="15" :lineDash="[]" lineCap="butt"></ol-style-stroke>
              <ol-style-fill color="rgba(255,255,255,0.5)"></ol-style-fill>
          </ol-style-circle>

          <ol-style-text>
              <ol-style-fill color="white"></ol-style-fill>
          </ol-style-text>
        </ol-style>
      </ol-animated-clusterlayer>
```

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by d-koppenhagen** [comment]
Hi, have you tried to use a custom `overrideStyleFunction`? With this function you should be able to style things individually.

**Comment by d-koppenhagen** [comment]
I will close this issue since there was no response. Feel free to re-open it with more information when the problem still exists.
