### ISSUE TITLE
Can not use with webpack-cdn-plugin

### ISSUE THREAD

**Issue by jiayp** [MelihAltintas/vue3-openlayers#77]
webpack config like this
```
       {
          name: 'vue3-openlayers',
          var: 'OpenLayersMap',
          path: 'dist/vue3-openlayers.umd.min.js',
        },

```

Got error :
```
Uncaught ReferenceError: OpenLayersMap is not defined
    at Object.vue3-openlayers (external var "OpenLayersMap":1:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module../src/main.js (.svg$:69:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:6:1
    at startup:6:1
```

**Comment by MelihAltintas** [comment]
Please give me a detail of the problem

**Comment by jiayp** [comment]
I'm using webpack-cdn-plugin for load vue3-openlayers from cdn in webpack's config.
And that plugin need a "var", but I can't find what is var vue3-openlayers uses.

**Comment by d-koppenhagen** [comment]
@jiayp does this problem still exists? meanwhile the lib has evolved.
Can you probably provide an example repo for minimal reproduction of the problem?

**Comment by d-koppenhagen** [comment]
I will close this issue for now. Please re-open if your problem still exists and provide steps to reproduce (ideally a Stackblitz project etc.)
