### ISSUE TITLE
Is there an option to load locally stored files (e.g. from indexedb as strings) into a xyz source

### ISSUE THREAD

**Issue by AlexanderBrese** [MelihAltintas/vue3-openlayers#80]
Hey there,

is there an option to load locally stored files (e.g. from indexedb as strings) into a xyz source? As of now it's possible to provide a template url but I need an option to provide data directly depending on coordinates given.

Something like:
```js
tileUrlOffline(coordinate: Array<string>) {
        return this.mapSettings[this.activeMap].tiles.find(
          (tile) =>
            tile.id ===
            `OSM_${coordinate[0]}_${coordinate[1]}_${-coordinate[2] - 1}`
        )
      },
`

**Comment by d-koppenhagen** [comment]
Would it help to pass-through a `tileLoadFunction`? Have a look at OpenLayers source:
https://openlayers.org/en/latest/apidoc/module-ol_source_XYZ-XYZ.html

**Comment by d-koppenhagen** [comment]
I will close this issue for now, since there was no response. @AlexanderBrese please share your solution if you were able to fix it. I think `tileLoadFunction` should do the trick.
