### ISSUE TITLE
Map is not visible after v-show

### ISSUE THREAD

**Issue by mostafaznv** [MelihAltintas/vue3-openlayers#91]
Hi.
Map works fine but when I'm using it in a multi-tab, map tiles doesn't render normally.

### To Reproduce

1. put map in a container
2. add `v-show` to container
3. set initial value of v-show to `false`
4. change v-show to `true`
5. map doesn't render 

### Screenshots

![image](https://user-images.githubusercontent.com/7619687/180422514-8009c327-5c11-4938-b5ab-cbcb031dc194.png)

### Platform

 - OS: macos
 - Browser: chrome
 - Version: 103.0.5060.134

### Link to reproduce bug
https://codesandbox.io/s/v-show-warning-forked-ritzum

**Comment by d-koppenhagen** [comment]
This seems to be a problem with the reactivity in your app and not with vu3-openlayers. Please make sure the boolean you are using for `v-show` is a `ref()`.
I provided a playground where you can see, the `v-show` works:
https://stackblitz.com/edit/vitejs-vite-9wrqog?file=src/components/TheMap.vue
