### ISSUE TITLE
Accessing a clicked feature's original object

### ISSUE THREAD

**Issue by boriskogan81** [MelihAltintas/vue3-openlayers#98]
Sorry about the cross-posting from Stackoverflow, but nobody is answering there.

I have a Vue 3 Composition API component using Vue Open Layers, iterating through an object array property on the component and creating a feature for each object. When a feature is selected, I want to access the original object's information, in this case, the name. How can I do this? Right now all I get access to is the array of coordinates which the feature was created from.
```
    <ol-map :loadTilesWhileAnimating="true" :loadTilesWhileInteracting="true" style="height:90vh; width: 80vw;" ref="map">

      <ol-view ref="view" :center="center" :rotation="rotation" :zoom="zoom" :projection="projection"/>

      <ol-tile-layer>
        <ol-source-osm />
      </ol-tile-layer>
      <ol-interaction-select @select="featureSelected" :condition="selectCondition" >
        <ol-style>
          <ol-style-stroke color="red" :width="10"></ol-style-stroke>
          <ol-style-fill color="rgba(255,255,255,0.5)"></ol-style-fill>
        </ol-style>
      </ol-interaction-select>

      <ol-geolocation :projection="projection" @positionChanged="geoLocChange">
        <template v-slot="slotProps">
          <ol-vector-layer :zIndex="0">
            <ol-source-vector>
              <ol-feature ref="positionFeature">
                <ol-geom-point :coordinates="slotProps.position"></ol-geom-point>
                <ol-style>
                  <ol-style-icon :src="hereIcon" :scale="0.1"></ol-style-icon>
                </ol-style>
              </ol-feature>
              <ol-feature v-for="(contract, index) in contracts" :key="index" >
                <ol-geom-polygon :coordinates="[contract.location]"></ol-geom-polygon>
                <ol-style>
                  <ol-style-stroke color="green" :width="5"></ol-style-stroke>
                </ol-style>
              </ol-feature>
            </ol-source-vector>

          </ol-vector-layer>
        </template>
      </ol-geolocation>
    </ol-map>

...

export default defineComponent({
  name: 'IndexPage',
  setup() {
    const contracts = [
      {
        name: "Tel Aviv traffic jams",
        location: [[34.742580, 32.046081],[34.760053,32.135796],[34.817236,32.127726],[34.783349,32.031719]]
      }
    ]
    const selectConditions = inject('ol-selectconditions')

    const selectCondition = selectConditions.click;
    const selectedContract = ref(false);


    const clickedFeature = (event) => {
      console.log(event);
    }

```

**Comment by boriskogan81** [comment]
@close

**Comment by boriskogan81** [comment]
#close

**Comment by Trayshar** [comment]
> #close

Did you find a soultion?

**Comment by mkarliner** [comment]
I have the same question/problem.
Any suggestions?

**Comment by Trayshar** [comment]
First you need a selection somewhere in your map that references an event handler:
```vue
<ol-interaction-select @select="featureSelected">
    ...
</ol-interaction-select>
```

Event handler (in TypeScript):
```ts
const featureSelected = (event: SelectEvent) => {
  // Make sure that event.selected is not empty before;
  // Its an array because you can select more than one feature
  // Getting 'myProperty' for the first selected feature
  const myProperty = event.selected[0].get('myProperty')
}
```

See [here](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select.SelectEvent.html) for documentation on SelectEvent

**Comment by mkarliner** [comment]
Hi @Trayshar , my question, and, I think the OP's, is that we can't attach an arbitary property to an ol-feature so that we can then refer back to other data about the feature held in other parts of the app.
So, for instance, I can't attach a data-foo="myserialno" attribute to an ol-feature because it renders fragments.

I have a 'ReportPoint' component that wraps an ol-feature thus:
<template>
  <ol-feature>
    <ol-geom-point :coordinates="coordinate"></ol-geom-point>
    <ol-style>
      <ol-style-circle :radius="radius">
        <ol-style-fill :color="fillColor()"></ol-style-fill>
        <ol-style-stroke
          :color="strokeColor"
          :width="strokeWidth"
        ></ol-style-stroke>
      </ol-style-circle>
    </ol-style>
  </ol-feature>
</template>

When I get the feature from the featureSelected event, I'd like to be able to get some reference to the metadata associated with the feature in the ReportPoint component or attach a prop to the ol-feature

I'm probably missing something obvious, or misunderstanding, but that is my  problem
thanks in advance.
Mike

**Comment by Trayshar** [comment]
Hi Mike (@mkarliner),
With the `properties` prop on `ol-feature` you can do just that, assign additional data to a feature. For your example, that would look like that:
```vue
<ol-feature :properties="{foo: 'myserialno'}">
```

You can then retrieve this data (any key-value pair you put into this properties object) using the method I posted above (which actually only works with the properties field, which I forgot to mention - sorry)

```ts
const featureSelected = (event: SelectEvent) => {
  // Make sure that event.selected is not empty before;
  // Its an array because you can select more than one feature
  // Getting 'myProperty' for the first selected feature
  const myserialno = event.selected[0].get('myserialno')
}
```

[Relevant Docs](https://openlayers.org/en/latest/apidoc/module-ol_Feature-Feature.html)

Hope this helps...
Trayshar

**Comment by boriskogan81** [comment]
Here is the somewhat hacky way I did this:

Template:

`              
      <ol-interaction-select @select="featureSelected" :condition="selectCondition" ref="selectInteraction">
        <ol-style>
          <ol-style-stroke color="red" :width="10"></ol-style-stroke>
          <ol-style-fill color="rgba(255,255,255,0.5)"></ol-style-fill>
        </ol-style>
      </ol-interaction-select>
      
      ...
      
      <ol-feature v-for="(contract, index) in contractStore.contracts" :key="featureKey(index)" :properties="contract"
                          ref="contracts">
                <ol-geom-polygon :coordinates="contract.coordinates" :key="contract.address"></ol-geom-polygon>
                <ol-style>
                  <ol-style-stroke color="green" :width="5"></ol-style-stroke>
                </ol-style>
              </ol-feature>
`
Script:

`
    const clickedFeature = (event) => {
      if (event.selected.length === 1 && event.selected[0].values_.id) {
        contractStore.selectContract(event.selected[0].values_.id);
        contractDialog.value = true;
      }
    };
    const featureSelected = (event) => {
      clickedFeature(event);
    };
`

The event.selected[0].values_ object holds all of the original properties.
