### ISSUE TITLE
Is this the only way to set doubleClickZoom?  map.value.map.interactions.array_[1].values_.active = false; 

### ISSUE THREAD

**Issue by vince-mock** [MelihAltintas/vue3-openlayers#99]

**Comment by d-koppenhagen** [comment]
Can you please provide a more detailled description with the context:
- What do you want to do?
- Example code how you are doing it right now

**Comment by d-koppenhagen** [comment]
As of no response, I will close this issue for now. Please re-open with more details (see comment before), when the problem still exists.
